### PR TITLE
Implement ex create image member openstack

### PR DESCRIPTION
**Pull request by vdloo**
implement ex_create_image_member and ex_accept_image_member in the OpenStack compute driver

### CODE REVIEW

**Comment by pquentin** [comment]
Thanks! Can you please fix the lint?

**Comment by vdloo** [comment]
done, build is now failing on something that looks unrelated (building the 'libvirtmod' extension). amended and force pushed once again to see if a rebuild fixes it 

edit: nope

**Comment by pquentin** [comment]
According to https://bugs.launchpad.net/openstack-requirements/+bug/1753539, pinning libvirt-python to 4.0.0 should fix our issue.

Do you think you could open a pull request wich replaces all `libvirt-python` occurrences to `libvirt-python==4.0.0` in tox.ini? That would be really helpful. Thanks!

**Comment by vdloo** [comment]
sure, see https://github.com/apache/libcloud/pull/1180. I rebased this branch on that branch

**Comment by pquentin** [comment]
Thanks! Merged into trunk. ✨

**Pull request closed without merging**
