### PR TITLE
EquinixMetal small fix to handle large instances RAM measured in TB

### PR DESCRIPTION
**Pull request by luss**
### Description

Replace this with the PR description (mention the changes you have made, why
you have made them, provide some background and any references to the provider
documentation if needed, etc.).

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.

### Status

Replace this: describe the PR status. Examples:

- work in progress
- done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by luss** [comment]
I've disccused this small fix to EquinixMetal with my friends at Equinix and they are supportive.

**Review by displague — APPROVED** [review]
lgtm.

The  specs in the general plan list only use GB today:
```
$ metal plans list -o json | jq -r '.[]|.specs.memory.total' | sort -n -u
null
16GB
32GB
64GB
128GB
192GB
256GB
384GB
512GB
768GB
1024GB
```
There are [workload-optimized](https://deploy.equinix.com/developers/docs/metal/hardware/workload-optimized-plans/) and custom reserved hardware instances that may have the memory spec written as this PR would address. This is a reasonable defensive patch. 

I verified that this raw python block handles the input.

@luss do you have instances that return the memory in this format today?

**Comment by displague** [comment]
@luss It seems we now have 3 Equinix Metal PRs up:
- #1970 
- #1971
- #1972

This PR's inclusion of 50c187e is complicating this PR and tying it to the features present in the other two PRs.  Can we remove that commit from this PR? 

For testing purposes, if you want to run with all of the PRs, I'd suggest using a different branch for that, one that is not opened as a PR.

**Comment by luss** [comment]
I'm not the worlds biggest git expert....   I will create a new PR from a clean repo that has only my suggest fix.  The I will withdraw this PR

**Pull request closed without merging**
