### PR TITLE
Set Softlayer create_node hourly value as boolean to pass to SL API

### PR DESCRIPTION
**Pull request by r2ronoha**
### Description

Set hourly in compute/drivers/softlayer.py to boolean to pass to the SL API

### Status

Done, ready for review

### Checklist (tick everything that applies)

- [X] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [X] Documentation
- [X] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)

```
libcloud anoha$ PYTHONPATH=. python libcloud/test/compute/test_softlayer.py
......................
----------------------------------------------------------------------
Ran 22 tests in 2.574s

OK
libcloud anoha$
```

### CODE REVIEW

**Comment by r2ronoha** [comment]
Fix for https://github.com/apache/libcloud/issues/1334

**Comment by Kami** [comment]
Thanks for contributing this bug fix.

It would also be good to add a test case which verifies that the parameter sent with the HTTP request is indeed a boolean.

**Comment by Kami** [comment]
To help you a bit, I added a test case in 9f5e972cf4f4e339d12d40204eb5d1b1638a64ff, 50579e0ea2430831f2556c0141dddc521b1212dc.

**Comment by Kami** [comment]
Merged, thanks.

**Pull request merged**
