### PR TITLE
[LIBCLOUD-813] create record and update record was not working

### PR DESCRIPTION
**Pull request by ghost**
### Description

Link to the bug report: https://issues.apache.org/jira/browse/LIBCLOUD-813

Following changes were required to get those working:
- Priority entry exists only at MX and SRV records
- Content type of submitted data had to be application/json
- Data parameter of connection request has to be string 
  Only MX and SRV records have pririoty. Cotent-type for data has to be json.  data param of connection request must be string, changed that.
### Status
- done, ready for review
  ### Checklist (tick everything that applies)
- [X ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [NA ] Documentation
- [X] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html) - executed
- [ NA] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by Kami** [comment]
Thanks, the changes look good to me.

If you get a chance it would also be good to add some tests which verify that the payload is indeed correct (you would need to assert this into the MockHttp class methods).

**Comment by ghost** [comment]
Actually all tests should be re-done because they didn't notice any critical bugs. Unfortunately I don't have time for that at the moment. LIBCLOUD-811 and -813 delayed me too much with my work.

**Comment by tonybaloney** [comment]
LGTM

**Comment by Kami** [comment]
@teemuvesala Yeah, I agree.

I recently also enabled pylint so this should also help with catching at least part of the similar issues in the future.

**Pull request closed without merging**
