### PR TITLE
Fix #LIBCLOUD-840

### PR DESCRIPTION
**Pull request by hcarlsso**
### Description

Trivial change 

### Status

- done, ready for review

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by tonybaloney** [comment]
see also #1052

**Comment by tonybaloney** [comment]
@hcarlsso you have trailing whitespace on 140 and 141

**Comment by hcarlsso** [comment]
The trailing whitespaces have been fixed in 823bb4f42e9d3d8e280e61daa9cd2fd94469fec9

**Comment by tonybaloney** [comment]
Merging. Thanks for the contribution!

**Pull request closed without merging**
