### PR TITLE
Support for AWS signature algorithm v4 (continuation)

### PR DESCRIPTION
**Pull request by Kami**
Continuation from https://github.com/apache/libcloud/pull/444/files#r25956437

The pull request is not finished yet, but it now works correctly with the "region" argument.

``` bash
# -------- begin 140069208370896 request ----------
curl -i -X GET -H 'Host: ec2.us-east-1.amazonaws.com' -H 'X-LC-Request-ID: 140069208370896' -H 'Accept-Encoding: gzip,deflate' -H 'User-Agent: libcloud/0.17.1-dev (Amazon EC2) ' --compress 'https://ec2.us-east-1.amazonaws.com:443/?SignatureVersion=2&...&Action=DescribeInstances'
# -------- begin 140069208370896:140069213157064 response ----------
HTTP/1.1 200 OK
Content-Encoding: gzip
Transfer-Encoding: chunked
Vary: Accept-Encoding
Server: AmazonEC2
Date: Sat, 07 Mar 2015 15:44:39 GMT
Content-Type: text/xml;charset=UTF-8

e6
<?xml version="1.0" encoding="UTF-8"?>
<DescribeInstancesResponse xmlns="http://ec2.amazonaws.com/doc/2013-10-15/">
    <requestId>59272782-d9ee-4367-91ee-c84dc782003f</requestId>
    <reservationSet/>
</DescribeInstancesResponse>
0

# -------- begin 140696717963408 request ----------
curl -i -X GET -H 'Host: ec2.eu-central-1.amazonaws.com' -H 'Accept-Encoding: gzip,deflate' -H 'X-AMZ-Date: 20150307T155439Z' -H 'X-LC-Request-ID: 140696717963408' -H 'Authorization: AWS4-HMAC-SHA256 Credential=.../eu-central-1/ec2/aws4_request, SignedHeaders=accept-encoding;host;user-agent;x-amz-date, Signature...' -H 'User-Agent: libcloud/0.17.1-dev (Amazon EC2) ' --compress 'https://ec2.eu-central-1.amazonaws.com:443/?Action=DescribeInstances&Version=2013-10-15'
# -------- begin 140696717963408:140696722668144 response ----------
HTTP/1.1 200 OK
Content-Encoding: gzip
Transfer-Encoding: chunked
Vary: Accept-Encoding
Server: AmazonEC2
Date: Sat, 07 Mar 2015 15:54:39 GMT
Content-Type: text/xml;charset=UTF-8

e6
<?xml version="1.0" encoding="UTF-8"?>
<DescribeInstancesResponse xmlns="http://ec2.amazonaws.com/doc/2013-10-15/">
    <requestId>f4b4b62c-23ab-4347-85a6-3d0cea18eea7</requestId>
    <reservationSet/>
</DescribeInstancesResponse>
0
```

TODO:
- [x] Update affected tests
- [x] Update affected code
- [x] Add new tests
- [x] Verify it works with non EC2 AWS services (storage, etc.)

### CODE REVIEW

**Comment by Kami** [comment]
@gertjanol This includes changes mentioned in #444, notably a84f57826fdf73c34b8ef6e98738f971dcc9a912 and 35ddbe17cab6fedc03718128b13298e7b64bb1de.

Do you guys still use "class per region" approach? If so, those changes will break it...

**Comment by allardhoeve** [comment]
@Kami, we can change it if we still use it.

**Comment by Kami** [comment]
@allardhoeve @gertjanol I've updated the affected code and tests. Can you guys please have a look and test it? :)

Thanks.

**Comment by Kami** [comment]
@allardhoeve @gertjanol ^^ bump

**Comment by Kami** [comment]
@allardhoeve @gertjanol I will go ahead and merge those changes today.

Please let me know if you encounter any issues.

**Comment by allardhoeve** [comment]
Sorry about the silence. We'll manage. Thanks.

**Pull request merged**
