### PR TITLE
Update GCE driver to API version v1beta16

### PR DESCRIPTION
**Pull request by wrigri**
Most of the changes are in the test fixtures, some were regenerated, some
just had URLs updated as necessary.  In addition, there were some changes made
to the tests to use the regenerated test fixtures.

### CODE REVIEW

**Comment by Kami** [comment]
Build is failing (https://travis-ci.org/apache/libcloud/builds/13388540) - can you please fix the lint issues?

**Comment by wrigri** [comment]
@Kami Fixed lint issue.  The build is green now, but let me know if you see any other issues.

**Comment by Kami** [comment]
@wrigri Merged, this PR cam be closed now.

Thanks!

**Comment by wrigri** [comment]
Thanks for the quick turnaround.  Closing PR.

**Pull request closed without merging**
