### PR TITLE
LIBCLOUD-392: Add support for keypairs management in the OpenStack drive...

### PR DESCRIPTION
**Pull request by schaubl**
JIRA issue: https://issues.apache.org/jira/browse/LIBCLOUD-392

### CODE REVIEW

**Comment by Kami** [comment]
@schaubl Sorry for the delayed, I've added a comment on JIRA - https://issues.apache.org/jira/browse/LIBCLOUD-392?focusedCommentId=13771950&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13771950

**Comment by Kami** [comment]
@schaubl Bump, any updates on this?

I would love to see this merged.

**Comment by schaubl** [comment]
@Kami I will do it in approximately one hour. Sorry for the delay.

**Comment by schaubl** [comment]
I did the requested changes

**Comment by Kami** [comment]
I've made the with change and merged patch into master.

Thanks!

**Comment by schaubl** [comment]
Thanks!

**Pull request closed without merging**
