### PR TITLE
[LIBCLOUD-684] Add auto-scale support for AWS and Softlayer providers

### PR DESCRIPTION
**Pull request by aviweit**
Link to JIRA: https://issues.apache.org/jira/browse/LIBCLOUD-684

### CODE REVIEW

**Comment by Kami** [comment]
Thanks.

As mentioned on IRC, I'm pretty busy these days, but I will try to have a look ASAP.

**Comment by aviweit** [comment]
OK, thanks.

**Comment by aviweit** [comment]
I have moved autoscale support to a new 'autoscale' folder per your recommendation in IRC. This is done under a new PR, with the same title, that I have just opened.

I will be happy to get your comments.

**Comment by Kami** [comment]
Great, thanks.

**Pull request closed without merging**
