### PR TITLE
[Google] Don't retry failed requests on auth when determining if GCE metadata server is available

### PR DESCRIPTION
**Pull request by Kami**
This pull request should help with an edge case / issue reported in #1591.

## Background, context

Right now if retrying failed HTTP requests is enabled globally (either via module level constant or via environment variable value), Libcloud will also try to retry a request inside ``_is_gce()`` on driver instantiation / authentication where we try to determine if GCE metadata server is available and what kind of auth credentials are provided by the user.

This is not desired when GCE metadata server is not available and a different type of credentials are used (e.g. oAuth 2).

## Proposed Approach

In this PR, I simply disable retrying failed requests for that code piece where we determine if metadata server is available.

I think this should be sufficient, but if needed / desired, we can add another argument to the driver constructor which would cause driver to skip this step all together (e.g. ``ex_don_check_gce_metadata_server``).

## TODO

- [x] Unit tests

### CODE REVIEW

**Comment by RunOrVeith** [comment]
sounds reasonable to me, but I actually think we could do something that doesn't require interaction.
According to [this documentation](https://developers.google.com/identity/sign-in/web/server-side-flow) Step 3, the IA user_id for the guess_type method always ends with "apps.googleusercontent.com",

so I would propose something like 
```python

class GoogleAuthType:
    ...
 
    @classmethod
    def guess_type(cls, user_id):
         ...
         elif cls._is_installed_application(user_id):
               return cls.IA
        elif cls._is_gce():
              # it's important that this is the last check, because it may take a long time if it fails and is retrying is enabled
              return cls.GCE
        else:
              # Either rise an error (not sure which one) or fall back to cls.IA again
              raise RuntimeError("Could not guess authentication scheme")

    @staticmethod
    def _is_installed_application(user_id):
        return user_id.endswith("apps.googleusercontent.com")

```

I tried it with an instance were I want to authenticate with IA and the ending is there in the user_id

**Comment by Kami** [comment]
@RunOrVeith Yeah, if that's the case and we can avoid that branch all together, that would be ideal.

I will dig into the docs and into making that change.

**Comment by Kami** [comment]
Re throwing exception in the else clause - I think in general that's a good idea (fail fast and loudly), but I'm slightly worried this may break some edge case since right now we fall back to ``cls.IA``.

So perhaps to be on the safe side, it's the best to leave ``else`` clause as is for now.

**Comment by RunOrVeith** [comment]
yes that was also my concern with the exception

**Comment by Kami** [comment]
@RunOrVeith This should probably do it - 0b8b22307526c185ebc372cd4d1cc5543eedbb6d.

To be on the safe side, I left else clause as it was before.

**Comment by RunOrVeith** [comment]
Looks good, except that the CI complains about the unsanitized url. Not sure how to fix that though.

**Comment by Kami** [comment]
@RunOrVeith Thanks for the review. I already marked that as "non an issue" in the Github UI.

**Pull request merged**
