### PR TITLE
Fix the bug that created the node at ecs driver and implement the method for creating public ip 

### PR DESCRIPTION
**Pull request by watermelo**
### Description
1, From the official document can know parameter param['IoOptimized'] type is string and his value is ``none`` or ``optimized``
Official document:
https://help.aliyun.com/document_detail/25499.html?spm=5176.doc25513.6.255.IAZjXA

2, Amend commit:
Implement the method for creating public ip. 

### Status
- done, ready for review

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by watermelo** [comment]
Looks like there is a problem in unit test, I need to modify the unit test .

**Comment by Kami** [comment]
Thanks!

The change looks good to me.

**Comment by watermelo** [comment]
hi!~ @Kami , I have modified the unit test

**Comment by watermelo** [comment]
Sorry, I'm not too familiar with github to cause no new branches to make a second commit. T.T

**Comment by tonybaloney** [comment]
👍 thanks @watermelo

**Pull request closed without merging**
