### PR TITLE
Add support for selecting alternate cloud_environments

### PR DESCRIPTION
**Pull request by tetron**
### Description

Add support for selecting alternate cloud_environments via "cloud_environments" keyword option when creating compute driver object. Supports default, AzureChinaCloud, AzureUSGovernment, and AzureGermanCloud.  Affects endpoints used by azure_arm compute driver.

### Status

- In testing

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [x] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [x] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by tonybaloney** [comment]
`urlparse` is a Python 2.7 specific standard library. We have a compatibility option in `libcloud.utils.py3`

**Comment by tetron** [comment]
Thanks, I'll see what I can do.

**Comment by tetron** [comment]
@tonybaloney is this ready to merge?

**Comment by tonybaloney** [comment]
@tetron please can you change the `__init__` keyword to `region` to keep it consistent with the ec2 driver and others.

**Comment by tetron** [comment]
Azure has two concepts: "location" and "cloud environment".  A cloud environment is a separately operated installation of Azure, it has a distinct set of endpoints and separate accounts.  Within a cloud environment there can be many locations (data centers).

When setting up a connection to Azure, it is only necessary to know the "cloud environment".  The "location" supplied in API requests that need it.

Currently `AzureNodeDriver` maps the `region` keyword to `location`, and accepts `cloud_environment` as an additional parameter which is passed through to `AzureResourceManagementConnection`.  If we renamed `cloud_environment` to `region` in `AzureResourceManagementConnection` that would give `region` an inconsistent meaning between the two classes.  

So we can either:

* Leave it as-is
* Merge cloud_environment and location into a single value for region (which gets split by the driver): user would specify `centralus` (use default) or `AzureChinaCloud/southchina` (use an alternate cloud environment). 
* Something else?

**Comment by tonybaloney** [comment]
sorry that's just my lack of understand of Azure, agreed 👍  merging.

**Pull request merged**
