### PR TITLE
[LIBCLOUD-663] List volume snapshots for openstack

### PR DESCRIPTION
**Pull request by allardhoeve**
Implement `list_volume_snapshots` using list comprehension on results of `ex_list_snapshots`.

### CODE REVIEW

**Comment by allardhoeve** [comment]
Also see related #451

**Comment by allardhoeve** [comment]
Rebased on trunk and squashed

**Comment by allardhoeve** [comment]
@kami, lint is misbehaving here as well I think

**Comment by Kami** [comment]
Merged into trunk. Thanks.

**Pull request closed without merging**
