### PR TITLE
LIBCLOUD-434: list_records() return all records for a Route53 zone.

### PR DESCRIPTION
**Pull request by xofer**
The Route53 API returns a maximum of 100 records per request. This change makes multiple requests to get all records in the zone when results are truncated.

### CODE REVIEW

**Comment by Kami** [comment]
Thanks, this looks like a good start, but it should be changed to match other drives and use a generator approach. This means implementing `iterate_zones` and `iterate_records` method.

`list_zones` and `list_records` doesn't need to be implemented in this case since it's already provided by a parent class.

You can find an example of how Zerigo driver does that here - https://github.com/apache/libcloud/blob/trunk/libcloud/dns/drivers/zerigo.py#L149

**Comment by Kami** [comment]
@xofer ^^ let us know if you need any help with this.

**Comment by xofer** [comment]
Thanks @Kami -- will give it a shot later today and let you know...

**Comment by Kami** [comment]
@xofer hey, have you made any progress on this?

Let us know if you need any help.

**Comment by xofer** [comment]
well, that's not what I wanted. Will open a new request.

**Comment by xofer** [comment]
@Kami https://github.com/apache/libcloud/pull/187

**Pull request closed without merging**
