### PR TITLE
[W.I.P] Make Rackspace drivers multi-datacenter aware 

### PR DESCRIPTION
**Pull request by Kami**
This branch does the following:
- Updates all the Rackspace drivers to use auth 2.0
- Updates all the Rackspace drivers to always use global auth endpoint
- Updates Rackspace compute driver to correctly handle `datacenter` kwarg with next gen driver and `region` kwarg with first gen driver
- Updates Rackspace storage driver to correctly handle `datacenter` kwarg

Still left to do and update:
- Update affected compute tests
- Update Loadbalancer drivers
- Update DNS drivers
- Eventually drivers which support that (every driver except first gen Cloud Servers driver) should be updated to user service catalog instead of hard-coded list of available datacenters

### CODE REVIEW

**Comment by rgbkrk** [comment]
Current version of libcloud appears to use 1.0 still. Have you made any more progress or created a ticket on Apache's JIRA?

**Comment by Kami** [comment]
@rgbkrk Yes, latest published version (0.13.2) still uses auth 1.0, but trunk includes those changes and uses auth 2.0.

Those changes (https://libcloud.readthedocs.org/en/latest/upgrade_notes.html#libcloud-0-14-0) will also be included in the next release (0.14.0) which is currently being voted on (http://mail-archives.apache.org/mod_mbox/libcloud-dev/201310.mbox/%3CCAJMHEmKfWmMgt0c0idmAbE6Fxg67cRTo-VbH4Y9djsk4J9X%3D%3Dg%40mail.gmail.com%3E).

**Comment by rgbkrk** [comment]
Oh sweet. Thanks @Kami! I'll start watching the mailing list too. I'm looking forward to this.

**Comment by Kami** [comment]
@rgbkrk You are welcome. And yeah, libcloud-dev is fairly low volume.

**Pull request closed without merging**
