### PR TITLE
[LIBCLOUD-632] Added images from ubuntu-os-cloud image project

### PR DESCRIPTION
**Pull request by dagi3d**
https://issues.apache.org/jira/browse/LIBCLOUD-632

### CODE REVIEW

**Comment by Kami** [comment]
LGTM

/cc @erjohnso

**Comment by erjohnso** [comment]
LGTM too.  @Kami - any chance we can get this merged for 0.16.0?

**Comment by Kami** [comment]
@erjohnso Sadly it's too late for 0.16.0 since the voting thread has already been started.

If it's a critical fix, we can just start a voting thread for 0.16.1 release once the 0.16.0 is out.

**Comment by Kami** [comment]
Merged into trunk. Thanks.

**Comment by erjohnso** [comment]
@Kami - no worries. I wouldn't call it 'critical', but I do suspect users are anxious to begin using Ubuntu on GCE.  I'll look into a patch to allow users to specify the image project so we don't have to keep hard-coding in image projects each time we come out with a new distro.

Thanks for the quick merge!

**Pull request closed without merging**
