### PR TITLE
Packet rebranding to Equinix Metal

### PR DESCRIPTION
**Pull request by dimgal1**
### Description
Update driver, tests and assets to reflect the Packet rebranding to Equinix Metal

### Status
done, ready for review

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [x] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [x] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by displague** [comment]
This looks good to me, if the preference is to leave a deprecated Packet driver in place, the old Packet drivers could take on the new API endpoints and continue working until the deprecation deadline is met.  There would be a minor change in the API results because the `href` values have changed.

I see more "Packet" references leftover in the code and documentation (`git grep -n -i packet`), there are also more "packet.net", "packet.com", "packethost.net", and "net.packet" references.  It's a tricky rename because TCP "packet" appears in several locations of the code.

The image `docs/_static/images/provider_logos/packet.png` should be updated to an Equinix Metal name and logo (`find . -name \*packet\*`).

Also, `libcloud/test/compute/test_equinixmetal.py` has two incorrect email address in the comment block.  The maintainer should be updated and the credit to jed@packet.com (@jedsmith) should be jed@linode.com (which isn't a current email address either).  This portion of the comment block can probably be removed.

**Comment by jedsmith** [comment]
My valid email is jed@jedsmith.org, if it’s helpful.

**Comment by dimgal1** [comment]
Thanks for the feedback. Just to summarize:
1. Regarding the deprecation of the old Packet driver, I think it's best for the maintainers to decide how to handle (@Kami?).
2. Regarding docs, most files seem to be auto-generated but I can't find guidelines on how to build and commit them. Any insights?
3. Regarding the image, the new one is already included. Didn't remove the old one because of (2) above.
4. Regarding the maintainer, @displague I see you work for Equinix. Will you pick up this role or should I leave it blank?
5. Regarding the reference to @jedsmith, I will update to the email address above.

**Comment by jedsmith** [comment]
Looks like someone copied over Linode code and did a `sed` to replace `linode` with `packet`, to explain the incorrect e-mail address for me. I've never been employed by Packet, and I'm relatively annoyed to have made this discovery this morning. Poor form. Nice catch, @displague.

Edit: [Here's where it came from.](https://github.com/apache/libcloud/commit/4d51ede113df6a16f55e1027726fe858aff1e8d5#diff-47fa639cd27b7d1b06fd76ccc4afb4ae4e7cbb273c7f4d689e5ccc2b18fec5fbR17)

**Comment by Kami** [comment]
Please add an entry to ``docs/upgrade_notes.rst`` which explains this change and provides info / examples on how to migrate / update the existing code.

**Comment by dimgal1** [comment]
Done!
I have added the new logo but left the old packet one. Should I remove it?
Also, is there anything else I should change?

**Comment by Kami** [comment]
Thanks for the contribution - this has now been merged into trunk.

**Pull request merged**
