### PR TITLE
multiple changes

### PR DESCRIPTION
**Pull request by marcinkuzminski**
Hope someone can review, cherry pick changes
- package is now using distribute so one can link sources using python setup.py develop
- basically implementation of few missing methods for brightbox
- zerigo dns improvements
- fixed openstack calls for networking API
- implementation of add,delete,list,create floating ips.

### CODE REVIEW

**Comment by Kami** [comment]
@marcinkuzminski First thanks for the pull request.

It would make it a lot easier for us if you can split this pull request into multiple one - one per group of related changes.

**Comment by marcinkuzminski** [comment]
yes i know, just don't have time to do that now, hope to do it next week or so.

**Comment by Kami** [comment]
@marcinkuzminski OK, let us know if you need any help down the road.

I've quickly glanced over the changes and there are some pep8 issues and missing tests, but besides that, they look good.

**Comment by Jc2k** [comment]
Just a note - distribute is now deprecated in favour of setuptools, so we can't really accept that one as is.

**Comment by marcinkuzminski** [comment]
yes we can throw those changes to setup.py away now.

**Comment by Kami** [comment]
I wanted to address those changes in more detail in a separate PR but
basically what John said.

Besides that the provided setup script has way too many nasty side affects
which shouldn't happen when you just run or import setup.py

sent from my mobile

**Comment by Kami** [comment]
@marcinkuzminski Any updates on this?

There are a bunch of useful changes which be good to have in trunk.

**Comment by marcinkuzminski** [comment]
Sorry about the lack of response here, i've been very busy recently + a lot of traveling. I Hope i force myself to split this stuff this week.

**Comment by marcinkuzminski** [comment]
I checked my PR and it seems all besides the brightbox changes were already merged/fixed. I'll close this one and open a new one with Brightbox changes.

**Comment by Kami** [comment]
Sounds good.

**Pull request closed without merging**
