### PR TITLE
Google Storage permissions support

### PR DESCRIPTION
**Pull request by crunk1**
- Added ex_(get|set|delete)_permissions to libcloud.storage.drivers.google_storage.GoogleStorageDriver
- Added a JSON connection to the GoogleStorageDriver.
- The JSON connection is only used in the new methods I added. Added tests for changes.

Tests:
python setup.py test
python3.4 setup.py test

### CODE REVIEW

**Comment by crunk1** [comment]
@adjackura @erjohnso

**Comment by crunk1** [comment]
@rickard-von-essen

**Comment by rickard-von-essen** [comment]
Don't think I should have been pinged here?

**Comment by crunk1** [comment]
Ah, yes. Sorry, about that, Rickard. I was looking over a previous bug patch we had discussed.

**Comment by crunk1** [comment]
@zmarano

**Comment by tonybaloney** [comment]
@crunk1 can you explain the motivations behind the PR please?

**Comment by crunk1** [comment]
Google Cloud Storage doesn't have a method exposed to query for, or set, permissions on containers or objects. This PR adds the functionality to do so. Internally at Google, I have built some libraries on top of libcloud and I need a way to get and set permissions on GCS entities.
IntEnum was a helper class that I made for my changes, but I purposefully made it more generalized and put it in common/types.py with the idea to share it.

**Comment by crunk1** [comment]
@illfelder

**Comment by erjohnso** [comment]
The IntEnum addition looks like it could be generically useful across more of the code base. I'm pretty sure I've used dicts and sorted key lists for things like this. But I wonder if it would be better to decouple this and introduce IntEnum more broadly (across more of libcloud) to help us all move to this model?  My concern with keeping it joined with the GCS changes, we'd all forget about it and the generic solution would not get adopted elsewhere at which point, this becomes a more complex solution than needed purely for the GCS changes.

wdyt?

/cc @supertom

**Comment by crunk1** [comment]
I think it is a little beyond the scope of this PR, but I agree with your opinion. Could I put it in a subsequent PR?

**Comment by erjohnso** [comment]
Yes please! I think teasing that out separately and doing something more basic for GCS now would be easier.

**Comment by crunk1** [comment]
PTAL, IntEnum logic and other cleanup removed from this PR.

**Comment by erjohnso** [comment]
Thanks @crunk1! 👯

**Pull request closed without merging**
