### PR TITLE
LIBCLOUD-606 Can not connect to AWS with IAM role temporary credentials

### PR DESCRIPTION
**Pull request by alejandrogr**
### Description

Can not connect to AWS with IAM role temporary credentials. Doesn't seem like the supplied token is in the header

From: [LIBCLOUD-606](https://issues.apache.org/jira/browse/LIBCLOUD-606)
### Status

done, ready for review
### Checklist (tick everything that applies)
- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by tonybaloney** [comment]
hi @alejandrogr thanks for the contribution, if you look at the test runs, every class that derived from this connection class (and didn't create a property `self.token`) is failing.

could you please add a supporting test for this scenario as well, the docs say that this is supported, so is this a bugfix or a new behaviour? http://libcloud.readthedocs.io/en/latest/compute/drivers/ec2.html#using-temporary-security-credentials

**Comment by Kami** [comment]
Good catch - thanks!

And yeah, what Anthony said wrt tests :)

**Comment by tonybaloney** [comment]
@alejandrogr can you run `flake8 --ignore=E402 --exclude=test libcloud/` locally and just check the linting errors please? Travis is giving a failure.

**Comment by alejandrogr** [comment]
Hi,

I've just checked the linting problems and solved them. I'm pretty new to python and libcloud so please let me know if something can be improved.

Should other derived drivers from BaseEC2NodeDriver supports the temporary token too?

Cheers

**Comment by Kami** [comment]
Merged into trunk, thanks.

For now, I think it's the best to only support token in the EC2 driver since I believe it's EC2-specific functionality.

**Pull request closed without merging**
