### PR TITLE
Clean compute drivers

### PR DESCRIPTION
**Pull request by ZuluPro**
### Description

Remove:

- [x] Bluebox
- [x] bsnlcloud
- [x] Cloudwatt
- [x] enomaly
- [x] elastichosts
- [x] elasticstack
- [x] Kili
- [x] gogrid
- [x] Gridspot
- [x] hostvirtual (now netactuate)
- [x] Joyent
- [x] med-1
- [x] nephoscale
- [x] 1and1 (now IONOS)
- [x] profitbricks (now IONOS)
- [x] ServerLove
- [x] skalicloud
- [x] Softlayer (now IBM)
- [x] Voxel

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.

### Status

Done

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [x] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [x] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by Kami** [comment]
@ZuluPro That's for the clean up - it's always good to remove dead / unused code :)

Would appreciate if you could provide some references which document that those providers are not active / alive anymore (I did quickly check some myself and it indeed looks the companies are either dead or pivoted into a different area).

**Comment by Kami** [comment]
I'm trying to sync this up with latest trunk, but it's turning out to be a bit of a pain due to the formatting changes in trunk.

**Comment by ZuluPro** [comment]
@Kami Yes I failed too. I'm really sorry to this branch like this.
Let me try to find a solution during the next week.

**Comment by Kami** [comment]
I believe I managed to address all the conflicts in #1852 (but I still need to go over the changes again and double check).

**Comment by Kami** [comment]
#1852 has been merged. Thanks a lot of this clean up!

**Pull request merged**
