### PR TITLE
[LIBCLOUD-1026] Update documentation for UpCloud driver

### PR DESCRIPTION
**Pull request by iler**
### Description

- Dropped www from the URL
- Added missing datacenters
- Updated API credentials instructions
- Updated logo

[https://issues.apache.org/jira/projects/LIBCLOUD/issues/LIBCLOUD-1026](
https://issues.apache.org/jira/projects/LIBCLOUD/issues/LIBCLOUD-1026)

### Status

- done, ready for review

### Checklist (tick everything that applies)

- [x] Documentation
- [x] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)
- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)

### CODE REVIEW

**Comment by vdloo** [comment]
Thanks! Merged in trunk. :sparkles:

**Comment by vdloo** [comment]
Ah shoot, should have waited for the tests my bad:
```
$ git clone --depth=50 https://github.com/apache/libcloud.git apache/libcloud
Cloning into 'apache/libcloud'...
remote: Enumerating objects: 3957, done.
remote: Counting objects: 100% (3957/3957), done.
remote: Compressing objects: 100% (2572/2572), done.
remote: Total 3957 (delta 1658), reused 3016 (delta 1323), pack-reused 0
Receiving objects: 100% (3957/3957), 5.63 MiB | 19.10 MiB/s, done.
Resolving deltas: 100% (1658/1658), done.
$ cd apache/libcloud
3.78s$ git fetch origin +refs/pull/1259/merge:
fatal: Couldn't find remote ref refs/pull/1259/merge
The command "eval git fetch origin +refs/pull/1259/merge: " failed. Retrying, 2 of 3.
fatal: Couldn't find remote ref refs/pull/1259/merge
The command "eval git fetch origin +refs/pull/1259/merge: " failed. Retrying, 3 of 3.
fatal: Couldn't find remote ref refs/pull/1259/merge
The command "eval git fetch origin +refs/pull/1259/merge: " failed 3 times.
The command "git fetch origin +refs/pull/1259/merge:" failed and exited with 128 during .
```
I'm sure this is fine though since it is just a textual change

**Comment by iler** [comment]
@vdloo just to make sure that I've understood the current contribution workflow correctly I should now make a patch out of this change and then attach the patch to the JIRA ticket?

**Comment by vdloo** [comment]
Hi @iler, no that is not necessary I think. I've merged your change into the trunk and pushed it to the Apache Software Foundation repositories. The way it works is that we don't merge directly on github but instead merge the commits to trunk, sign the commits, and then once we push it the asfgit bot will come by to sync the repo back to github and close the pull request. Your change is now [in the current trunk](https://github.com/apache/libcloud/commit/dd6aaba856d5f3ed6e8a05c4f92465a968af450d) and the change has been documented [here in the CHANGES file](https://github.com/apache/libcloud/commit/080b343e0983f2a22f7647b4fd8cebb3339adbe2). What should happen in relation to the JIRA ticket and how the documentation is used to generate the readthedocs website I do not know.

**Comment by iler** [comment]
@vdloo Ok, I'm cool with that. Was just following the instructions found from the documentation at [https://libcloud.readthedocs.io/en/latest/development.html#attach-a-final-patch-with-your-changes-to-the-corresponding-jira-ticket](https://libcloud.readthedocs.io/en/latest/development.html#attach-a-final-patch-with-your-changes-to-the-corresponding-jira-ticket)

**Pull request closed without merging**
