### PR TITLE
[LIBCLOUD-965] /v3/OS-FEDERATION/projects deprecated in OpenStack OIDC auth

### PR DESCRIPTION
**Pull request by micafer**
### Description

As stated here:
https://developer.openstack.org/api-ref/identity/v3-ext/#list-projects-a-federated-user-can-access

The path: /v3/OS-FEDERATION/projects has been deprecated in v1.1. Use core GET /auth/projects. This call has the same response format.

Also added response.body as body of the MalformedResponseError to improve error messages in case of non expected response code.

### Status

- done, ready for review

### Checklist (tick everything that applies)

- [X] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by pquentin** [comment]
@micafer Thank you for your contribution!

Unfortunately the old path is no longer covered by tests. Are the OpenStack versions that need the old path still supported? If yes, we need somehow two tests to test the two paths. If it can be removed, then let's do that!

I don't have other issues with your code. Thanks!

**Comment by micafer** [comment]
Hi @pquentin ,
I have added a new test to cover the old path.

**Review by pquentin — APPROVED** [review]

**Comment by pquentin** [comment]
Thanks! Merged in trunk. ✨ Can you please close the LIBCLOUD issue? I can't do that myself.

**Comment by micafer** [comment]
LIBCLOUD issue closed!

**Pull request closed without merging**
