### PR TITLE
Feature ssl offload

### PR DESCRIPTION
**Pull request by snmpboy**
### Description

Added the ability to add certificates and keys to NTTC-CIS load balancer service.  Requires pyopenssl

### Status

Replace this: describe the PR status. Examples:

- done, ready for review

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [x] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [x] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by snmpboy** [comment]
I have two pull requests to be reviewed.  I also had my original work merged into the trunk on 10/30 but it didn't make it into 2.4.0 release.

**Comment by tonybaloney** [comment]
I think you forked this off the #1253 branch? Can you rebase against develop and cherry-pick only the changes in this PR, unless that is, the other PR is required to be merged before this one?

**Comment by snmpboy** [comment]
Removed the separate drs driver.  Ready to merge.

**Comment by snmpboy** [comment]
Can someone please review this?  Thanks!

**Comment by tonybaloney** [comment]
the pyopenssl dependency, is that specific to this driver?

I assume the RSA private keys in this pull request are test data :-)

**Comment by snmpboy** [comment]
@tonybaloney Yes, it is specific to the nttcis loadbalancer driver.  Those keys and crts are test data and self signed.  Is there any requirements or restrictions on importing python modules, whether built-in or third party installed?  I have another branch using python-dateutil.  Thanks!

**Comment by tonybaloney** [comment]
Unless there's a reason that benefits multiple drivers, we really try to avoid adding extra dependencies to this project.

Another alternative is to make it option, like the vsphere/pysphere package https://github.com/apache/libcloud/blob/trunk/libcloud/compute/drivers/vsphere.py#L28-L39

**Comment by snmpboy** [comment]
@tonybaloney  Pyopenssl has been made optional, but has been placed in tox.ini similar to pyvsphere.

**Comment by tonybaloney** [comment]
👍

**Pull request closed without merging**
