### PR TITLE
Add description to ex_authorize_security_group_ingress (same for all …

### PR DESCRIPTION
**Pull request by r2ronoha**
…cidrIps)

### Description

Added 'description' parameter to the ex_authorize_security_group_ingress method.
If provided, it will add the given description to the cidr_ip's affected by the insertion

### Status

- done, ready for review
- future work could be done to add the possibility of add a different description to each cidr_ip in the the ipranges

### Checklist (tick everything that applies)

- [X] [Code linting]
- [ ] Documentation
- [X] [Tests] Tested on our aws integration
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by pquentin** [comment]
Thank you @r2ronoha for your interest in libcloud. We're happy that you chose this project for your first GitHub contribution! ✨ 

The change itself is nice, thanks! Two things are missing before we can integrate it in libcloud:

* describe the new description parameter in the docstring of `ex_authorize_security_group_ingress`
* add an automated test for the new parameter. I'm happy to hear that you tested it on your AWS integration, but we need an automated test to ensure that your change continues to work in the future. See `test_authorize_security_group_ingress` in `libcloud/test/compute/test_ec2.py` and the corresponding `libcloud/test/compute/fixtures/ec2/authorize_security_group_ingress.xml` fixture.

Make sure to ask for help if anything is unclear.

**Comment by pquentin** [comment]
@r2ronoha Thanks! We're nearly there.

Is the description expected to appear in the response when you're using the real EC2 service? Ideally, the test should ensure that the description was actually taken into account, possibly using fake EC2 requests (test fixtures).

Oh, and the lint does not pass, see https://travis-ci.org/apache/libcloud/jobs/283747844 which says "libcloud/compute/drivers/ec2.py:7454:27: E128 continuation line under-indented for visual indent".

**Comment by pquentin** [comment]
@r2ronoha Any progress on this? Thanks.

**Comment by r2ronoha** [comment]
@pquentin I have made a quick update to solve the lint issue

**Comment by pquentin** [comment]
Thank you! Merged in trunk. ✨

**Comment by r2ronoha** [comment]
Excellent @pquentin Do we know when this will be available?

**Comment by pquentin** [comment]
@r2ronoha I would like to release a new version before the end of July, we'll see if that happens! (We would new maintainers to maintain a faster pace.)

**Comment by r2ronoha** [comment]
Cool, thx for the info

**Pull request closed without merging**
