### PR TITLE
Support not using standard projects on images get.

### PR DESCRIPTION
**Pull request by illfelder**

### CODE REVIEW

**Comment by erjohnso** [comment]
Thanks for this @illfelder! Please squash into a single commit and then I'll merge it in.

**Comment by illfelder** [comment]
Updated to be a single commit.

**Comment by erjohnso** [comment]
Fooey. I just merged (commit 7013b6a190c0017ab13e0cea95a36eaeceb2abb2), but forgot to update the commit message so it would auto-close this PR.

Please manually close when you confirm the change is merged to trunk.

Thanks again Max!

**Comment by illfelder** [comment]
Confirmed! Thanks!

**Pull request closed without merging**
