### PR TITLE
LIBCLOUD-415 try fix keypair delete

### PR DESCRIPTION
**Pull request by gigimon**
Hello

I think this fix delete keypair in Eucalyptus (ticket https://issues.apache.org/jira/browse/LIBCLOUD-415)

### CODE REVIEW

**Comment by Kami** [comment]
The pull request looks good, but it needs a test case which verifies that right query parameters are sent to the server (in this case, that is `KeyName`).

Also next time when making a changes like this, please link to a reference guide on the provide page (in this case, that would be http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-query-DeleteKeyPair.html).

**Comment by gigimon** [comment]
Test for this function already in trunk, this "patch" fix set up a arguments correspondence to api docs

**Comment by Kami** [comment]
@gigimon Yes, but the existing test case (https://github.com/apache/libcloud/blob/trunk/libcloud/test/compute/test_ec2.py#L382), doesn't test that the right arguments are sent to the API which is the important part in this case.

You can see an example of how other tests do that here - https://github.com/apache/libcloud/blob/trunk/libcloud/test/compute/test_ec2.py#L709

**Comment by gigimon** [comment]
please check, I added test for arguments

**Comment by Kami** [comment]
@gigimon Looks good. Please attach this patch to the JIRA issue and I'll merge it into trunk.

**Comment by gigimon** [comment]
@Kami  complete, please see in JIRA

**Comment by Kami** [comment]
@gigimon Merged, this pr can be closed now.

Thanks.

**Comment by gigimon** [comment]
Ok, Thx!

**Pull request closed without merging**
