### PR TITLE
Azure ARM deployment

### PR DESCRIPTION
**Pull request by famanson**
## Azure ARM deployment
- Add the new Resource Management deployment to Azure code to replace the classic one that has too many limitations

### CODE REVIEW

**Comment by tonybaloney** [comment]
woah. Ok, please can you give me a little description over what is in this PR @famanson ?

**Comment by famanson** [comment]
@tonybaloney eh? This was supposed to be an internal PR into our fork... I think I'll close this PR and come back when this has been polished

**Comment by Denvar94** [comment]
@tonybaloney Hey, as you might be able to tell @famanson  and I are trying to build a driver for the newer API. We were wondering whether you know how we can contact the libcloud developers or anyone who would be willing to collaborate/help us push our work upstream? We currently have something that works specifically for our own uses, but is not a finished product to be merged.

**Comment by tonybaloney** [comment]
That would be me (or anyone else that merges PRs). 
Do you have a list of outstanding changes?

**Comment by tonybaloney** [comment]
@famanson you probably picked the wrong upstream, so you raised a PR against the actual apache/libcloud repository. It makes sense now why the patch doesn't work as your trunk is probably also out of sync with the apache/libcloud trunk. We'll need to get that aligned as well.

**Comment by famanson** [comment]
@tonybaloney yeah, github UI defaulted to libcloud upstream (I created the PR from there). We'll work on getting everything ready for a proper push

**Comment by Denvar94** [comment]
@tonybaloney We're basically a driver for the newer Azure API https://msdn.microsoft.com/en-gb/library/azure/dn790568.aspx. At the moment @famanson has built just enough so that the following functions work:
    - `list_locations`
    - `list_sizes`
    - `list_nodes`
    - `create_node`
The main differences between this at the existing Azure driver are the API calls and handling the json requests and responses. We would need help in finishing the other functions and also deploying Windows VMs, because currently the code only allows Linux VMs to be deployed.

**Comment by morissette** [comment]
I would like to get involved with this integration I have done the 
following:
- list_nodes
- list_sizes
- list_images
- ex_start_node
- ex_stop_node
- reboot_node
- destroy_node

In addition I use the proper Azure SDK instead of direct rest calls 
which I believe is a bit more maintainable and readable, snippet:

https://bpaste.net/show/cc6df02c43b7

Let me know your thoughts and what the steps moving forward should be.

**Comment by Denvar94** [comment]
@morissette We’re only doing the API on our branch at the moment, that's what works for us. You can have look at what we've done so far https://github.com/esplorio/libcloud

**Pull request closed without merging**
