### PR TITLE
Create SpanishREADME-es.md

### PR DESCRIPTION
**Pull request by haucke**
### Description

Replace this with the PR description (mention the changes you have made, why
you have made them, provide some background and any references to the provider
documentation if needed, etc.).

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.
### Status

Replace this: describe the PR status. Examples:
- work in progress
- done, ready for review
### Checklist (tick everything that applies)
- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

ReadMe in Spanish for coders who are ESL.

### CODE REVIEW

**Comment by tonybaloney** [comment]
I think the file should be called README-es.md

**Comment by tonybaloney** [comment]
And thanks for the contributions.

**Comment by pquentin** [comment]
@tonybaloney Clearly this was done for Hacktoberfest last year. Is this useful? How do ensure it stays in sync? The English README still has a PyPI download counter even though this statistic has long been disabled by PyPI.

**Comment by pquentin** [comment]
@haucke For what it's worth, the request was to change the file name, not the pull request title.

**Pull request closed without merging**
