### PR TITLE
auroradns: Set connection context in various functions

### PR DESCRIPTION
**Pull request by wido**
This makes sure that the Exception has the proper information

### CODE REVIEW

**Comment by sebgoa** [comment]
maybe a test ?

**Comment by wido** [comment]
@runseb Worked on tests for AuroraDNS this weekend. I can include this PR in there?

**Comment by sebgoa** [comment]
yes , just force push to your PR and squash.

**Comment by wido** [comment]
I'll close this one and submit a new PR shortly with tests and these fixes.

**Pull request closed without merging**
