### PR TITLE
LIBCLOUD-439

### PR DESCRIPTION
**Pull request by sebgoa**
Adds extra attributes to the node instance. Namely image_id, image_name, size_id, size_name and changes zoneid to zone_id and securitygroup to security_group.

Note that ec2 and openstack driver seem to use camelcase for extra attributes...

Updated tests to reflect these changes

### CODE REVIEW

**Comment by Kami** [comment]
@runseb Build is failing. Can you please have a look?

**Comment by sebgoa** [comment]
Ok I pushed a commit to fix this. whitespace issue

**Comment by Kami** [comment]
@runseb There still appears to be an issue in the tests (https://travis-ci.org/runseb/libcloud/jobs/15603187) :)

**Comment by Kami** [comment]
Squashed and merged, thanks!

**Pull request closed without merging**
