### PR TITLE
allow creds to be passed in dict

### PR DESCRIPTION
**Pull request by bassdread**
Allow the GCE driver to be created by passing existing tokens.

### CODE REVIEW

**Comment by wrigri** [comment]
Seems like a good change to me.  It would be great to have some documentation about how/when to use it, perhaps by adding a 4th example to this page: https://github.com/apache/libcloud/blob/trunk/docs/compute/drivers/gce.rst

**Comment by bassdread** [comment]
@Kami @wrigri hi, I have cleaned up the code and added docs and example code. Could you have another look?

**Comment by erjohnso** [comment]
@wrigri - can you take a look?

**Comment by wrigri** [comment]
Sorry, I've been away from libcloud for a while.  This looks good to me, but I'd imagine that it will need a few updates to allow it to be patched in cleanly.

**Pull request closed without merging**
