### PR TITLE
Add ec2 x1.32xlarge instance type

### PR DESCRIPTION
**Pull request by anze3db**
### Description

This pull request adds support for Amazon's newly announced instance type [x1.32xlarge](https://aws.amazon.com/about-aws/whats-new/2016/05/now-available-x1-instances-the-largest-amazon-ec2-memory-optimized-instance-with-2-tb-of-memory/).
### Status
- done, ready for review
### Checklist (tick everything that applies)
- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by anze3db** [comment]
Updating pricing.json with `scrape-ec2-prices.py` caused multiple tests to fail, because some prices that were previously set are now `N/A`. I have reverted these changes for now, but please let me know if I should look into the failing tests some more (probably as a part of another PR). 

Here is one example of a failing test:

```
======================================================================
ERROR: test_create_node_response (libcloud.test.compute.test_ec2.EC2APNETests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/apache/libcloud/libcloud/test/compute/__init__.py", line 71, in test_create_node_response
    size = self.driver.list_sizes()[0]
  File "/home/travis/build/apache/libcloud/libcloud/compute/drivers/ec2.py", line 2765, in list_sizes
    price = self._get_size_price(size_id=instance_type)
  File "/home/travis/build/apache/libcloud/libcloud/compute/base.py", line 1526, in _get_size_price
    size_id=size_id)
  File "/home/travis/build/apache/libcloud/libcloud/pricing.py", line 147, in get_size_price
    price = float(pricing[size_id])
ValueError: invalid literal for float(): N/A
```

**Comment by Kami** [comment]
Thanks for the contribution.

I will look into the pricing issue. Sadly Amazon doesn't have an official API for instance pricing so we resort on some (not so robust) price scrapping...

**Comment by Kami** [comment]
I thought they maybe removed support for those instance types in some regions, but it doesn't seem so. Pricing is still available on the pricing page, but not in the pricing javascript / JSON files.

I will update the code so it can also handle cases when pricing is not available.

**Comment by Kami** [comment]
Made the changes above and merged your PR into trunk.

Thanks!

**Comment by anze3db** [comment]
Awesome, thank you! :)

**Pull request closed without merging**
