### PR TITLE
[LIBCLOUD-876] Added new AWS region to compute driver

### PR DESCRIPTION
**Pull request by morissette**
### Description
Added us-east-2 region to AWS as ec2_us_east_ohio based on how oregon region was handled in existing code base.

### Status
- done, ready for review

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [x] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)

### CODE REVIEW

**Comment by tonybaloney** [comment]
build failure is nothing to do with this PR. 👍

**Comment by morissette** [comment]
See the docs pulled but not the actual change.

**Comment by tonybaloney** [comment]
it gets a new hash when applied with git-am 
https://github.com/apache/libcloud/commit/8140f8218486a767e953d084a3025fc990c65728 
@morissette

**Comment by morissette** [comment]
Ahh awesome, havent used git-am before.

**Pull request closed without merging**
