### PR TITLE
LIBCLOUD-504: Add support for records with multiple values such as MX/...

### PR DESCRIPTION
**Pull request by cderamus**
...NS records as well an additional fixture and test.

### CODE REVIEW

**Comment by Kami** [comment]
I was actually thinking about that in the past.

If we want to make it consistent across all the drivers, each value should be exposed as a separate record (that's how it currently works with other drivers).

For example:
- record 1: name=None, value=ASPMX.L.GOOGLE.COM., extra['priority']=1
- record 2:  name=None, value=ALT1.ASPMX.L.GOOGLE.COM., extra['priority']=5
- etc.

**Comment by cderamus** [comment]
Gotcha, that makes sense. I'll update this shortly.

**Comment by Kami** [comment]
I've merged changes to trunk, thanks.

While I was at it, I also made some changes to parse / handle SRV records better.

**Comment by cderamus** [comment]
Ah great call, thanks!

**Pull request closed without merging**
