### PR TITLE
[docs] Added link to Azure cross-platform CLI; updated CLI commands to reflect current version.

### PR DESCRIPTION
**Pull request by SamuelMarks**

### CODE REVIEW

**Comment by tonybaloney** [comment]
👍  thanks sam

**Comment by SamuelMarks** [comment]
@tonybaloney Actually I've found a few actual issues with the Azure doc, updating it now.

**Comment by tonybaloney** [comment]
@SamuelMarks we need some test fixtures for ARM if you're using the module and fancy recording the responses?

**Comment by SamuelMarks** [comment]
Happy to help out with that starting next Monday. This week is crazy :call_me_hand:

**Comment by SamuelMarks** [comment]
Made some time for this. Here you go: https://github.com/apache/libcloud/pull/1042

**Pull request closed without merging**
