### PR TITLE
Add eu-central-1 to EC2 drivers

### PR DESCRIPTION
**Pull request by JamesGuthrie**
Signed-off-by: James Guthrie james@prodigi.ch

### CODE REVIEW

**Comment by ralphbean** [comment]
Why did this get closed?

**Comment by JamesGuthrie** [comment]
Because it's outdated. Unfortunately the documentation hasn't been updated to reflect the change in the API though, and I only realised after making the PR that the documentation is outdated and my PR redundant.

The change is (mentioned [here](https://libcloud.readthedocs.org/en/latest/changelog.html#changes-with-apache-libcloud-0-14-0-beta3)) is:

> Deprecate the following EC2 provider constants: EC2_US_EAST, EC2_EU, EC2_EU_WEST, EC2_AP_SOUTHEAST, EC2_AP_NORTHEAST, EC2_US_WEST_OREGON, EC2_SA_EAST, EC2_SA_EAST and replace it with a new EC2 constant. Driver referenced by this new constant now takes a “region” argument which dictates to which region to connect.

So the following example (lifted from the docs):

```
cls = get_driver(Provider.EC2_US_WEST)
driver = cls('temporary access key', 'temporary secret key', token='temporary session token')
```

becomes:

```
cls = get_driver(Provider.EC2)
driver = cls("auth key", "auth secret", token="token", region="us-west-1")
```

So the driver type is no longer used to determine the location which the driver connects to. Instead, if you specify a valid region, that is the region it connects to. Valid regions are: 
- eu-west-1
- sa-east-1
- ap-southeast-2
- us-west-1
- us-east-1
- ap-southeast-1
- ap-northeast-1
- us-gov-west-1
- eu-central-1
- us-west-2

**Comment by JamesGuthrie** [comment]
I've opened #606 to fix the docs.

**Comment by ralphbean** [comment]
Thanks @JamesGuthrie.  I wandered down the same path you did!

**Comment by JamesGuthrie** [comment]
No problem! Hopefully you will be the last to do so.

**Pull request closed without merging**
