### PR TITLE
Issue LIBCLOUD-465: Add EC2 I2 instance type data into pricing.json

### PR DESCRIPTION
**Pull request by cderamus**

### CODE REVIEW

**Comment by Kami** [comment]
Are those instances already available? IIRC, they were announced during re:invent, but they haven't been officially available / launched yet.

If they are, `INSTANCE_TYPES` and `REGION_DETAILS` dicts in `libcloud.compute.ec2` should be updated as well.

**Comment by cderamus** [comment]
Ah, nice catch there! Yes I just received the E-mail from AWS this morning stating there availability in all regions with the exception of GovCloud (US) and South America (São Paulo). I'll go ahead and update the dictionaries momentarily.

**Comment by Kami** [comment]
Sounds good, thanks.

**Comment by Kami** [comment]
Looks good.

I've squashed the commits and merged the changes into trunk. This pull request can be closed now.

Thanks!

**Pull request closed without merging**
