### PR TITLE
Fixed the creation of nodes can not specify bandwidth bug

### PR DESCRIPTION
**Pull request by watermelo**
### Description
When InternetChargeType is `PayByBandwidth`, we can not specify `InternetMaxBandwidthOut`.

### Status
- done, ready for review

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by watermelo** [comment]
The following unit-test error do not seem to me, should I need to repair?

************\* Module libcloud.common.azure_arm

E:119,12: Too many positional arguments for method call (too-many-function-args)

**Comment by tonybaloney** [comment]
this is not your fault @watermelo , the build is broken on trunk. will be fixed and then you have to rebase.

**Comment by watermelo** [comment]
@tonybaloney  thank you~😄

**Comment by tonybaloney** [comment]
trunk is fixed, can you please rebase. If you've not done this before, I would do something like this:

``` bash
git checkout trunk
git fetch https://github.com/apache/libcloud.git trunk:upstream
git merge upstream
```

**Comment by watermelo** [comment]
great~👍👍👍

**Comment by tonybaloney** [comment]
changes LGTM 👍

**Comment by tonybaloney** [comment]
merged. in future I recommend creating a local branch instead of working on changes in trunk. it'll stop you from getting blocked on trunk.

**Comment by watermelo** [comment]
thanks for your recommendation.^_^

**Pull request closed without merging**
