### PR TITLE
Added AWS EC2 c5 series

### PR DESCRIPTION
**Pull request by ZuluPro**
### Description

New serie available:
- https://aws.amazon.com/fr/ec2/instance-types/c5/
- https://aws.amazon.com/fr/blogs/aws/now-available-compute-intensive-c5-instances-for-amazon-ec2/

### Status

Done!
Tests are failing due to depencencies issues.

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [x] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [x] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by ZuluPro** [comment]
@Kami @pquentin @tonybaloney 
Any news ?

**Comment by ZuluPro** [comment]
I fixed the unit test troubles in #1150.
You can re-run the test and appreciate success

**Comment by ZuluPro** [comment]
@pquentin @tonybaloney 
I think this PR is now mergeable.

**Comment by pquentin** [comment]
Thank you @ZuluPro and sorry for the hassle.

**Pull request closed without merging**
