### PR TITLE
Fixes LIBCLOUD-963

### PR DESCRIPTION
**Pull request by byronyi**
See https://github.com/apache/libcloud/pull/1163#issuecomment-385246605 for the rationale.

@mjjohnson1 @pquentin @tonybaloney @crunk1 Any comments?

### CODE REVIEW

**Comment by pquentin** [comment]
Please fix the lint, add a link to LIBCLOUD-963, and add tests. Thanks!

**Comment by byronyi** [comment]
Close this for now.

**Comment by byronyi** [comment]
Re-open to coordinate design and implementation process of the [`gke` module in Ansible](https://github.com/ansible/ansible/issues/39486), especially on refurnishing of `gce.ex_create_multiple_nodes` and `gce.ex_create_instancetemplate` APIs for the new keyword parameters.

**Comment by mjjohnson1** [comment]
LGTM

**Comment by tonybaloney** [comment]
Seen this down the queue. @byronyi is this PR still relevant?

**Pull request closed without merging**
