### PR TITLE
Fixing Python 2.6 unit testing and fixing Google tests.

### PR DESCRIPTION
**Pull request by crunk1**
@erjohnso 
@jimbobhickville

### CODE REVIEW

**Comment by jimbobhickville** [comment]
+1 - looks like you covered everything I found and then some.

**Comment by jimbobhickville** [comment]
Btw, this should fix https://issues.apache.org/jira/browse/LIBCLOUD-776 - I forget the exact syntax you put in the commit message to have it automatically close the ticket, but I believe there's a way to do that.

**Comment by tonybaloney** [comment]
:+1: looks much cleaner

**Comment by crunk1** [comment]
Sorry, still working on it. I have been able to repro it on python2.6. Still fixing atm.

**Comment by crunk1** [comment]
It appears that unittest in python 2.6 does not have setUpClass...

**Comment by crunk1** [comment]
Interesting... libcloud/testing/__init__.py:27 shows that they try to mitigate that problem with python 2.6's unittest module by importing unittest2 (which is 2.7's module). But that seems to not be working.

@Kami comment?

**Comment by crunk1** [comment]
Could be setup.py:21. It looks like the TestRunner is getting imported from Python 2.6's unittest module, which would explain why setUpClass isn't being called.

**Comment by crunk1** [comment]
@Kami please take a look at my change to setup.py.

**Comment by Kami** [comment]
@crunk1 setup.py change looks good to me - good catch!

**Comment by erjohnso** [comment]
:+1: LGTM too, thanks @crunk1 and @jimbobhickville 

I ran through tests on both Mac and my GCE debian instance and it all checks out.  Merging it in now.

**Pull request closed without merging**
