### PR TITLE
LIBCLOUD-764: Return proper volume state for CloudStack volumes

### PR DESCRIPTION
**Pull request by wido**
Map the 'state' value being returned by the CloudStack to a
libcloud StorageVolumeState.

### CODE REVIEW

**Comment by wido** [comment]
@runseb Can you take a look?

**Comment by sebgoa** [comment]
@wido this looks good, I will merge your few PRs tomorrow. Waiting to get 0.19.0 shipped so we can get a clean "restart".

**Comment by wido** [comment]
@runseb Great! I've got more stuff coming after these.

**Comment by wido** [comment]
@runseb Did you have a chance to take a look at this one?

**Pull request closed without merging**
