### PR TITLE
[LIBCLOUD-667] - Allow filtering in AWS list_iamges

### PR DESCRIPTION
**Pull request by katrielt**
Pull request for https://issues.apache.org/jira/browse/LIBCLOUD-667

### CODE REVIEW

**Comment by sebgoa** [comment]
Hi @katrielt can you check your patch and make sure all tests pass. It seems that the travis tests are failing, but it may not be due to your patch. thanks

**Comment by katrielt** [comment]
After rebasing to trunk, lint tests passed, as well as python2.6/python2.7 (Only interpreters I have installed)

**Comment by allardhoeve** [comment]
I think the failure to build is unrelated to the patch. I suggest we merge it.

@katrielt: can you try rebaseing one more time, please? There were a lot of pep8 fixes lately. Sorry about the hassle.

**Comment by katrielt** [comment]
Seems lint is failing globally now because of some dependency issues between pep8 an flake8. After some tinkering on my own system, I was able to get flake8 to run and lint passed.

**Comment by allardhoeve** [comment]
Some days ago someone fixated the pep8 dependency and that at least fixed
most my branches.

What tinkering did you do?

**Comment by katrielt** [comment]
Edit: 

libcloud/.tox/lint/lib/python2.7/site-packages/flake8-2.4.0.dist-info/METADATA
libcloud/.tox/lint/lib/python2.7/site-packages/flake8-2.4.0.dist-info/metadata.json 

and manually updated the pep8 requirement to >=1.5.7,<1.7

The right way is probably to update flake8

**Comment by sebgoa** [comment]
Looks like @Kami fixed the pep8 issue, so I am merging this cc: @katrielt @allardhoeve let's keep an eye on Travis to make sure it passes. thanks for the patch

**Pull request closed without merging**
