### PR TITLE
Fix proxy_url error #1336

### LINKED ISSUE #1336: Error with proxy_url in OpenStack auth
## Summary

An error appears when using some OpenStack auth classes where this new ``proxy_url`` parameter has not been added.

Error introduced in commit: c20cf0180dbd30fb4010aba259746808576f9aa8 from PR ##1324.

## Detailed Information

I get the error when trying to use the OpenStackIdentity_3_0_Connection_OIDC_access_token class. But it will appear using any other auth classes where the ``proxy_url`` parameter has not been added.

The error shown is:
```python
  File "/libcloud/compute/drivers/openstack.py", line 417, in ex_get_node_details
    resp = self.connection.request(uri, method='GET')
  File "/libcloud/common/openstack.py", line 225, in request
    raw=raw)
  File "/libcloud/common/base.py", line 538, in request
    action = self.morph_action_hook(action)
  File "/libcloud/common/openstack.py", line 292, in morph_action_hook
    self._populate_hosts_and_request_paths()
  File "/libcloud/common/openstack.py", line 305, in _populate_hosts_and_request_paths
    osa = self.get_auth_class()
  File "/libcloud/common/openstack.py", line 206, in get_auth_class
    parent_conn=self)
TypeError: __init__() got an unexpected keyword argument 'proxy_url'

```

### PR DESCRIPTION
**Pull request by micafer**
### Description

See issue: #1336

Resolves #1336 

### Status

- done, ready for review

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [x] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by Kami** [comment]
Thanks for fixing this.

I wonder how none of the existing tests caught this regression...

**Comment by Kami** [comment]
@gvengel do you happen to also use the OpenStack driver?

If so, it would be great if you could also test if proxy url works correctly with the OpenStack drivers (including the identity endpoints and connections).

**Comment by Kami** [comment]
Merged, thanks.

**Comment by gvengel** [comment]
@kami No, we don't use OpenStack in house. I'll see if I can get a single node Swift server setup quickly and give it a test.

**Comment by gvengel** [comment]
@Kami Okay, I got around to setting up a test OpenStack Swift server. Looks like all the proxy code is working great in trunk. I was able to upload through the proxy with both the `proxy_url` method and using the `http_proxy` environment variable. Just in case, I also tested HTTP and HTTPS Swift endpoints. 👍

**Comment by Kami** [comment]
@gvengel Thanks for testing and confirming :+1:

**Pull request merged**
