### PR TITLE
Add NodeBase base class for Node, NodeImage, and NodeSize

### PR DESCRIPTION
**Pull request by keiko713**
Add NodeBase base class for Node, NodeImage, and NodeSize to inherit from in order to share the get_uuid function and common attributes.

### CODE REVIEW

**Comment by Kami** [comment]
Hey, @tildedave actually had a good suggestion on the IRC.

It would be better for `NodeBase` to be a mixin instead of a base class. Here is an example of a Mixin class we use in tests - https://github.com/apache/libcloud/blob/trunk/test/compute/__init__.py#L20. Also, better name for this class would be `UuidMixin`.

Edit: Basically, I would do the following:
1. Name the base class `UuidMixin`
2. Remove `__init__` and `__repr__` method and just keep `get_uuid` method
3. Update affected code

**Comment by keiko713** [comment]
Hi, Tomaz. Thank you for your advice. I agree with that suggestion, I'm gonna change and I'll commit again.

**Comment by Kami** [comment]
This patch has been merged, you can close this pull request now.

Thanks

**Comment by Kami** [comment]
(just doing some pull request cleanup)

@keiko713 - Those changes have been merged a long time ago, can you please close this pull request?

Thanks!

**Comment by keiko713** [comment]
Sure thing!

**Pull request closed without merging**
