### PR TITLE
Add missing test_requirement "requests_mock" to setup.py

### PR DESCRIPTION
**Pull request by felixonmars**
### Description

requests_mock is needed and defined in test_requirements.txt, but is missing from setup.py. Let's keep them consistent.

### Status
done, ready for review

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [x] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [x] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by pquentin** [comment]
👍 

@tonybaloney There are other inconsistencies, should they be fixed too?

**Comment by tonybaloney** [comment]
well. yes there are inconsistencies, but they shouldn't necessarily be fixed. This a disagreement in the Python community, should `python setup.py install` install the dependencies for the package to execute _only_ or a full development environment.

I think they should be separate because you're probably installing from source and I don't want all of our users to have to install the dependencies we need for development (such as test runners and mockers).

**Comment by felixonmars** [comment]
But we are looking into test_requires here, which only applies to the test suite. `requests_mock` in the PR is being imported explicitly in multiple files and the test suite will just break without it installed.

**Comment by tonybaloney** [comment]
ah ok yes that should be updated. @pquentin which other inconsistencies?

**Comment by pquentin** [comment]
@tonybaloney I only noticed that test_requires (TEST_REQUIREMENTS) is different from requirements-tests.txt.

**Comment by tonybaloney** [comment]
👍  merging

**Pull request closed without merging**
