### PR TITLE
Allow passing `credential_file` to be used in the GCEConnection

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Is this PR waiting on additional input from me, ie, is there something missing? wrong? I can fix it, just let me know,

**Comment by erjohnso** [comment]
Not that @Kami has to wait for me, but I was going to do some quick tests this week and then give an LGTM.

**Comment by s0undt3ch** [comment]
Oh, OK! No worries ;)

**Comment by erjohnso** [comment]
Well, so. I was a bit off on my timing, sorry @s0undt3ch.

@Kami - LGTM to merge!

**Comment by s0undt3ch** [comment]
No problem!

**Comment by Kami** [comment]
@s0undt3ch Sorry for the delay - I was traveling and missed the LGTM comment.

**Comment by s0undt3ch** [comment]
No worries.

**Pull request closed without merging**
