### PR TITLE
[LIBCLOUD-598] IOError, 'Not a gzipped file' on LINODE driver

### PR DESCRIPTION
**Pull request by juancarlosm**

### CODE REVIEW

**Comment by Kami** [comment]
It would be great to see the debug log (https://libcloud.readthedocs.org/en/latest/troubleshooting.html#debugging) - can you please gist it? I'm curious on which requests this happens.

**Comment by Kami** [comment]
Travis build also failed with some lint issues which need to be fixed.

**Comment by juancarlosm** [comment]
Hi Tomaz,

I have removed whitespace that causes travis build failure.

LIBCLOUB_DEBUG output:

curl -i -X GET -H 'Host: api.linode.com' -H 'X-LC-Request-ID: 21342184' -H 'Accept-Encoding: gzip,deflate' -H 'User-Agent: libcloud/0.14.1 (Linode) ' --compress 'https://api.linode.com:443/?api_key=*****&api_responseFormat=json&api_action=linode.list'

# -------- begin 21342184:21343480 response ----------

HTTP/1.1 200 OK
Strict-Transport-Security: max-age=31536000
X-Powered-By: Tiger Blood
Transfer-Encoding: chunked
Content-Encoding: gzip
Vary: Accept-Encoding
Server: nginx/1.1.19
Connection: keep-alive
Date: Fri, 18 Jul 2014 09:33:24 GMT
Content-Type: application/json;charset=UTF-8

{"ERRORARRAY":[],"DATA":[{"ALERT_CPU_ENABLED":1,"ALERT_BWIN_ENABLED":1,"ALERT_BWQUOTA_ENABLED":1,"BACKUPWINDOW":0,"ALERT_DISKIO_THRESHOLD":1000,"DISTRIBUTIONVENDOR":"Debian","WATCHDOG":1,"DATACENTERID":7,"STATUS":1,"ALERT_DISKIO_ENABLED":1,"CREATE_DT":"2013-11-12 10:32:05.0","TOTALHD":98304,"ALERT_BWQUOTA_THRESHOLD":80,"TOTALRAM":2048,"ALERT_BWIN_THRESHOLD":5,"LINODEID":424154,"ALERT_BWOUT_THRESHOLD":5,"ALERT_BWOUT_ENABLED":1,"BACKUPSENABLED":0,"ALERT_CPU_THRESHOLD":90,"PLANID":0,"BACKUPWEEKLYDAY":0,"LABEL":"*****","LPM_DISPLAYGROUP":"","TOTALXFER":4000}],"ACTION":"linode.list"}

Traceback (most recent call last):
  File "./ecm_ecc.py", line 2933, in <module>
    sys.exit(main())
  File "./ecm_ecc.py", line 72, in main
    return ecc.dispatch()
  File "./ecm_ecc.py", line 2095, in dispatch
    return method(options, arguments)
  File "./ecm_ecc.py", line 100, in cmd_check_provider
    self.connection.list_nodes()
  File ".libcloud/compute/drivers/ecm_linode.py", line 119, in list_nodes
    data = self.connection.request(API_ROOT, params=params).objects[0]
  File ".libcloud/common/base.py", line 687, in request
    response = responseCls(**kwargs)
  File ".libcloud/common/linode.py", line 91, in **init**
    headers=self.headers)
  File ".libcloud/common/base.py", line 172, in _decompress_response
    body = decompress_data('gzip', body)
  File ".libcloud/utils/compression.py", line 39, in decompress_data
    return gzip.GzipFile(fileobj=cls(data)).read()
  File "/usr/lib/python2.6/gzip.py", line 212, in read
    self._read(readsize)
  File "/usr/lib/python2.6/gzip.py", line 255, in _read
    self._read_gzip_header()
  File "/usr/lib/python2.6/gzip.py", line 156, in _read_gzip_header
    raise IOError, 'Not a gzipped file'

curl -i -X GET -H 'Host: api.linode.com' -H 'X-LC-Request-ID: 38551424' -H 'Accept-Encoding: gzip,deflate' -H 'User-Agent: libcloud/0.14.1 (Linode) ' --compress 'https://api.linode.com:443/?api_key=*****&api_responseFormat=json&api_action=avail.datacenters'
HTTP/1.1 200 OK
Server: nginx/1.1.19
Date: Fri, 18 Jul 2014 09:47:34 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: Tiger Blood
Vary: Accept-Encoding
Content-Encoding: gzip
Strict-Transport-Security: max-age=31536000

{"ERRORARRAY":[],"DATA":[{"LOCATION":"Dallas, TX, USA","DATACENTERID":2,"ABBR":"dallas"},{"LOCATION":"Fremont, CA, USA","DATACENTERID":3,"ABBR":"fremont"},{"LOCATION":"Atlanta, GA, USA","DATACENTERID":4,"ABBR":"atlanta"},{"LOCATION":"Newark, NJ, USA","DATACENTERID":6,"ABBR":"newark"},{"LOCATION":"London, England, UK","DATACENTERID":7,"ABBR":"london"},{"LOCATION":"Tokyo, JP","DATACENTERID":8,"ABBR":"tokyo"}],"ACTION":"avail.datacenters"}

**Comment by Kami** [comment]
Thanks and sorry for the delay.

@fly is it possible for you to look into that? It looks like an issue / misconfiguration on the Linode side and I would actually prefer to have it fixed there.

**Comment by Kami** [comment]
I just tested this myself and it only happens when using `LIBCLOUD_DEBUG`.

I believe it's actually just an issue / mishandled edge case in LoggingConnection class. I will dig into it later.

You can validate that Linode does in fact return a gzipped response by running a cURL command manually and dropping `--compress` flag.

**Comment by Kami** [comment]
I've pushed a fix in eec3cc2b0edf93e547739534869f4f4c23244e4e.

It had nothing to do with Linode API after all. The problem was that Linode driver overrides `Response.__init__` and didn't correctly handle response body when using `LoggingConnection` (`LoggingConnection` is used when `LIBCLOUD_DEBUG` environment variable is specified).

Down the road, I also want to remove duplicated logic in `LinodeResponse.__init__` and just rely on the base `Response` class which handles all the known edge cases correctly.

@JuanCarlosM Thanks anyway.

@fly Ignore my last comment :)

**Pull request closed without merging**
