### PR TITLE
Update libvirt_driver.py

### PR DESCRIPTION
**Pull request by fitati**
the fonction destroy in libvirt dont take flags argument

### CODE REVIEW

**Comment by Kami** [comment]
Can you please provide a link to some reference documentation which says destroy doesn't take any argument?

Thanks

**Comment by fitati** [comment]
this is the libvirt official api reference link for destroy node,
i have tray it and it work very well,
http://libvirt.org/html/libvirt-libvirt.html#virNodeDeviceDestroy
cordially

2013/4/21 Tomaz Muraus notifications@github.com

> Can you please provide a link to some reference documentation which says
> destroy doesn't take any argument?
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/apache/libcloud/pull/101#issuecomment-16715923
> .

## 

Aymen Fitati
engineering student
at National School of Computer Science
ENSI-TUNISIA
phone: (+216) 53 83 15 11/26 83 40 40
skype: aymen.fitati

**Comment by Kami** [comment]
I've merged this patch into trunk - http://svn.apache.org/viewvc?view=revision&revision=r1470327. You can close this pull request now, thanks.

For the EC2 change and future contributions please open a ticket on our issue tracker (https://issues.apache.org/jira/browse/LIBCLOUD) and attach your patch there - thanks.

**Comment by fitati** [comment]
Hello,
there is another update for libcloud_driver on git, can you please validate,
for start node, the stopped node haven't an Id, this why we cannot start
node from her id, here is no ID !!
we need to look_up domain for name and start the virtual domaine
cordially

2013/4/21 Tomaz Muraus notifications@github.com

> I've merged this patch into trunk -
> http://svn.apache.org/viewvc?view=revision&revision=r1470327. You can
> close this pull request now, thanks.
> 
> For the EC2 change and future contributions please open a ticket on our
> issue tracker (https://issues.apache.org/jira/browse/LIBCLOUD) and attach
> your patch there - thanks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/apache/libcloud/pull/101#issuecomment-16738474
> .

## 

Aymen Fitati
engineering student
at National School of Computer Science
ENSI-TUNISIA
phone: (+216) 53 83 15 11/26 83 40 40
skype: aymen.fitati

**Comment by Kami** [comment]
@fitati Thanks, but I'll need more time to check this one and make sure it actually works and doesn't break anything.

Currently there are no tests for libvirt driver so it's hard to do that. I will try to get some tests to trunk asap, but it would also be great if you can add some tests for this new / updated functionality.

**Comment by fitati** [comment]
Hi,
about the test, i found this bug when I am trying to test this feature, but
if you get a look on libvirt api you found:

def lookupByID(self, id):
        """Try to find a domain based on the hypervisor ID number
        Note that this won't work for inactive domains which have an ID of
-1,
        in that case a lookup based on the Name or UUId need to be done
instead. """
        ret = libvirtmod.virDomainLookupByID(self._o, id)
        if ret is None:raise libvirtError('virDomainLookupByID() failed',
conn=self)
        __tmp = virDomain(self,_obj=ret)
        return __tmp
this is the source code and than you cannot get the virtual domaine with
this method and than you cannot start the node,
the solution id to get the virtual by his name
Cordially.

2013/4/25 Tomaz Muraus notifications@github.com

> @fitati https://github.com/fitati Thanks, but I'll need more time to
> check this one and make sure it actually works and doesn't break anything.
> 
> Currently there are no tests for libvirt driver so it's hard to do that. I
> will try to get some tests to trunk asap, but it would also be great if you
> can add some tests for this new / updated functionality.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/apache/libcloud/pull/101#issuecomment-17039768
> .

## 

Aymen Fitati
engineering student
at National School of Computer Science
ENSI-TUNISIA
phone: (+216) 53 83 15 11/26 83 40 40
skype: aymen.fitati

**Comment by Kami** [comment]
(just doing some pull request cleanup)

@fitati - Those changes are not relevant anymore, can you please close this pull request?

Thanks!

**Pull request closed without merging**
