### PR TITLE
Update Documentation for Google Compute Engine

### PR DESCRIPTION
**Pull request by wrigri**
It appears as though the supported_providers pages are generated, so I didn't edit those, but I'm not clear on exactly how they are generated (they would need to be updated to pick up the "website" change and the link to the gce driver documentation).

Also, I'm getting a warning that the loadbalancer doc isn't included in any toctree, but I'm not sure where to add it.

### CODE REVIEW

**Comment by Kami** [comment]
@wrigri I get a bunch of merge conflicts when I try to merge this patch. Can you please synchronize this branch with trunk?

**Comment by wrigri** [comment]
@Kami Let me know if that worked how you expected it to.  (Git still surprises me sometimes and doesn't do what I expect).  If not, I can always start over with a new pull request and a single check-in.

Also, I still have this test failure:
Warning, treated as error:
/home/travis/build/apache/libcloud/docs/loadbalancer/drivers/gce.rst:: WARNING: document isn't included in any toctree

And I'm not really sure how to fix it, so I'd appreciate any guidance you have on that.

**Comment by wrigri** [comment]
@Kami  OK, I think the fix for the test failure is:
cp docs/compute/drivers/index.rst docs/loadbalancer/drivers/.

In docs/loadbalancer/drivers/index.rst:
s/Compute/Load Balancer/

Does that seem right to you?

**Comment by Kami** [comment]
@wrigri Thanks, I'll have a look in a bit.

As far as the the second issue goes, running `./contrib/generate_provider_feature_matrix_table.py` script should fix it (I can do that).

This script will update a supported providers page and include a link to the gce driver documentation.

**Comment by Kami** [comment]
@wrigri Yeah, you are correct, doing that should fix it.

In any case, I'm already on it. I still had problems applying the patch cleanly, but I'll justly directly merge the branch.

**Comment by wrigri** [comment]
@Kami  OK, let me know if you need anything else from me on this.

**Comment by Kami** [comment]
@wrigri I've merged changes into trunk so I don't need anything else from you. Thanks!

**Pull request merged**
