### PR TITLE
LIBCLOUD-425: update linode api

### PR DESCRIPTION
**Pull request by bsdlp**
[LIBCLOUD-425](https://issues.apache.org/jira/browse/LIBCLOUD-425)

Update Linode API responses, most notably a few bugfixes for DNS responses, as well as update Linode plan ID numbers.

### CODE REVIEW

**Comment by Kami** [comment]
@fly Thanks, besides the lint issues (https://travis-ci.org/apache/libcloud/jobs/13222251), it looks good.

Please address those, squash the commits, attach patch to the jira ticket and I'll merge it into trunk.

**Comment by bsdlp** [comment]
done. Thanks @Kami

**Comment by Kami** [comment]
Merged into trunk, this PR can be closed now.

Thanks!

**Comment by bsdlp** [comment]
<3

**Pull request closed without merging**
