### PR TITLE
[LIBCLOUD-880] Add a method for retrieving rates on Azure.

### PR DESCRIPTION
**Pull request by sorenisanerd**
### Description

Azure has an API for retrieving rates. This patch exposes it.

### Status

- done, ready for review

### Checklist (tick everything that applies)

- [X] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [X] Documentation
- [X] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [N/A] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by supertom** [comment]
@sorenh I'm not an Azure user, but I did pull in this PR and then ran tox.  LGTM. :-)

**Comment by tonybaloney** [comment]
cool. good idea casting to a set in the test ;0) merging

**Comment by Kami** [comment]
@sorenh Btw, do you happen to be the same Soren who used to be the maintainer of the libcloud Ubuntu package (even before the Apache days and early Apache days if memory serves me right)?

If yes, thanks for that as well :)

**Comment by sorenisanerd** [comment]
@Kami Yes, that was me. :) You're very welcome. :+1:

**Pull request closed without merging**
