### PR TITLE
GCE: Retrieve regions & zones lazily, closes #1661

### LINKED ISSUE #1661: GCENodeDriver zone & region related attributes
## Feature Request

Currently the GCE driver populates its `zone_list`, `zone_dict`, `region_list`, `region_dict` attributes on driver initialization.

It would be better if these attributes were populated outside of init and only when needed.

### PR DESCRIPTION
**Pull request by dimgal1**
### Description

Implements #1661

### Status
- done, ready for review

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [x] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Review by dpeschman-godaddy — COMMENTED** [review]
Nice change!  Can you add some unit tests for the new properties?

**Comment by dimgal1** [comment]
Done @dpeschman-godaddy

**Review by dpeschman-godaddy — APPROVED** [review]
Thank you!

**Review by Kami — APPROVED** [review]

**Comment by Kami** [comment]
LGTM, thanks. And thanks to @dpeschman-godaddy for a review.

**Pull request merged**
