### PR TITLE
Openstack updates for Keystone 3 and Nova 2.x

### PR DESCRIPTION
**Pull request by tonybaloney**
## Openstack updates for Keystone 3 and Nova 2.x

This is a test for version 12 of OpenStack

* Testing Nova 2.1 API
* Adding 2.0, 2.1 and 2.2 as a valid `api_version`
* Giving a better error for the identity HTTP : 300 response that you'll receive

cc @allardhoeve

### CODE REVIEW

**Comment by pquentin** [comment]
It looks like there are unrelated commits in this pull request?

**Comment by tonybaloney** [comment]
I created the branch before I pushed my changeset upstream. I'll rebase @pquentin

**Review by allardhoeve — COMMENTED** [review]
Looks good, but let me test it against our stack

**Comment by pquentin** [comment]
Tried example_openstack.py as I would be interested to use libcloud for Openstack Swift: we currently use libcloud for Google Cloud Storage but python-swiftclient for Openstack Swift (hosted on OVH).

We currently authenticate using Keystone v2: https://docs.openstack.org/developer/python-swiftclient/client-api.html#keystone-v2. This requires an auth url (https://auth.cloud.ovh.net/v2.0/), user, key, tenant name and auth version (2). Why does libcloud require a base url? I don't know what it is. Also not sure why the tenant id is not in the example.

Anyway, with or without valid credentials and with or without a base url, `python demos/example_openstack.py` says:

```
[<NodeLocation: id=0, name=, country=, driver=OpenStack>]
Traceback (most recent call last):
  File "demos/example_openstack.py", line 15, in <module>
    pprint(con.list_images())
  File ".../libcloud/libcloud/compute/drivers/openstack.py", line 282, in list_images
    self.connection.request('/images/detail').object, ex_only_active)
  File ".../libcloud/libcloud/common/openstack.py", line 223, in request
    raw=raw)
  File ".../libcloud/libcloud/common/base.py", line 536, in request
    action = self.morph_action_hook(action)
  File ".../libcloud/libcloud/common/openstack.py", line 290, in morph_action_hook
    self._populate_hosts_and_request_paths()
  File ".../libcloud/libcloud/common/openstack.py", line 324, in _populate_hosts_and_request_paths
    osa = osa.authenticate(**kwargs)  # may throw InvalidCreds
  File ".../libcloud/libcloud/common/openstack_identity.py", line 1029, in authenticate
    method='POST')
  File ".../libcloud/libcloud/common/base.py", line 637, in request
    response = responseCls(**kwargs)
  File ".../libcloud/libcloud/common/base.py", line 157, in __init__
    message=self.parse_error())
libcloud.common.exceptions.BaseHTTPError: {"error": {"message": "get_version_v2() got an unexpected keyword argument 'auth'", "code": 400, "title": "Bad Request"}}
```

Am I doing something wrong? Is this the wrong pull request to look at? I don't really know what I'm doing except that python-swiftclient works and libcloud does not appear to work.

**Comment by allardhoeve** [comment]
Quentin, I agree this needs work.

Thanks for the feedback.

**Comment by tonybaloney** [comment]
@pquentin @allardhoeve  trying to stick with 1 change at a time, did this introduce any _new_ issues in OpenStack implementation?

**Comment by pquentin** [comment]
It was not working, and it is still not working. I can't tell, sorry not to be helpful.

**Comment by pquentin** [comment]
I would be happy to see this merged, @tonybaloney. It really improves tests, too: all tests inheriting from `OpenStack_1_0_Tests` are not discovered. I don't think this introduces new issues and the code looks fine.

I guess`Use PyTest as the unit testing runner` should be removed, though?

**Comment by tonybaloney** [comment]
merging

**Pull request merged**
