### PR TITLE
The hostname should be fullyQualifiedDomainName instead of hostname

### PR DESCRIPTION
**Pull request by RoelVanNyen**
Otherwise we don`t know which machine this really is, you only see a part of the hostname.

### CODE REVIEW

**Comment by Kami** [comment]
@RoelVanNyen Can you please update the failing tests?

Thanks

**Comment by RoelVanNyen** [comment]
Should be fixed now.

Thanks

**Comment by Kami** [comment]
@RoelVanNyen Actually, sorry. I just quickly glanced over this the first time.

I think a better approach would be to store this value in the `extra['hostname']` attribute.

**Comment by RoelVanNyen** [comment]
If you go to the softlayer panel and check the hosts you will see the names are equal to the fullyQualifiedDomainName and not the hostname, so it would be logical for me to use host['fullyQualifiedDomainName'] instead. Howhever if you really don`t want to do this then I would suggest putting the field into extra['fullyQualifiedDomainName'] instead of extra['hostname'].

What do you think?
Thanks

**Comment by Kami** [comment]
@RoelVanNyen Ah, if the Softlayer control panel uses `fullyQualifiedDomainName` for the display name, then using that in Libcloud makes sense as well.

**Comment by Kami** [comment]
Commits squashed and merged into trunk. Thanks.

**Comment by RoelVanNyen** [comment]
Cool. However I don`t see your commit anywhere.
Where is it committed ?

Cheers,

**Comment by phamnamlong** [comment]
Hi @RoelVanNyen, I find this fix quite problematic. Imagine the following scenario:

You create a node by: 

```
host = conn.create_node(name="first", image=image, size=size) 
```

Then, later you want to find this node by name:

```
def found_with_id(id):
  nodes = conn.list_nodes();
    for node in nodes:
      if node.name == id: # this is where the originally created name is not what it is now
        return node
  return None
```

Doesn't it break the generic purpose of libcloud where you will certainly have to "if conn is the SoftLayer" then check node.name == id + "example.com".

I suggest that the name is still the original created name while you will add extra attribute fullyQualifiedDomainName instead.

**Pull request closed without merging**
