### PR TITLE
refactored _parse_arp_table

### PR DESCRIPTION
**Pull request by Katana-Steel**
refactoring of the arp table parsing for libvirt
### Description

passing each command output to their own parsing function
and add unittest for parsing the tables
### Status
- done, ready for review
### Checklist (tick everything that applies)
- [X] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [X] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

split _parse_arp_table into 1 general and 2 specialized functions

### CODE REVIEW

**Comment by Katana-Steel** [comment]
I looked at other compute driver tests, but wasn't able to determine how to write a stub test for this driver

**Comment by Kami** [comment]
Thanks for doing that!

As far as the tests go - it will be a different in this case since libvirt driver uses libvirt library and doesn't talk directly to an HTTP API.

One thing which would help is if you can gist (or paste it here) the output of both commands (arp and ip neigh) - this way we can use this as fixtures for ip table parse test case.

**Comment by Katana-Steel** [comment]
I've only obfuscated the IP addresses a little, and only included the first 4 entries...
I think that should be enough to see the pattern

```
~ $ ip neighbor 
1.2.10.80 dev br0 lladdr 52:54:00:bc:f9:6c STALE
1.2.10.33 dev br0 lladdr 52:54:00:04:89:51 REACHABLE
1.2.10.97 dev br0 lladdr 52:54:00:c6:40:ec DELAY
1.2.10.40 dev br0 lladdr 52:54:00:77:1c:83 STALE

~ # arp -an
? (1.2.10.80) at 52:54:00:bc:f9:6c [ether] on br0
? (1.2.10.33) at 52:54:00:04:89:51 [ether] on br0
? (1.2.10.97) at 52:54:00:c6:40:ec [ether] on br0
? (1.2.10.40) at 52:54:00:77:1c:83 [ether] on br0
```

**Comment by Katana-Steel** [comment]
@Kami  added the command output

**Comment by Katana-Steel** [comment]
@Kami I've added a skeleton for a libvirt_driver test class with 2 actual tests.
Let me know what you think

**Comment by Kami** [comment]
Thanks and sorry for the delay - I will look into it asap.

**Comment by tonybaloney** [comment]
Changes LGTM :+1:

**Pull request closed without merging**
