### PR TITLE
Option to provision node with subnetwork

### PR DESCRIPTION
**Pull request by larsla**
### Description

This PR relates to #780, but adds the option to specify a subnetwork when creating a node.
### Status
- done, ready for review
### Checklist (tick everything that applies)
- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by erjohnso** [comment]
Holy moly @larsla - this is awesome timing and thank you!  I was just starting my day by getting ready to do this myself, but now I can watch cat videos on youtube instead! 👍 

Did you want to take a pass at adding tests for this? If not, I'm happy to do that (since I planned to do it anyway).

**Comment by larsla** [comment]
:)

I didn't have time to look at the tests yet, so please go ahead if you like.

**Comment by erjohnso** [comment]
Works for me. I'll work of your stuff.

**Comment by erjohnso** [comment]
@larsla - let me know if this works for you.  If you're happy with it and get it added to your branch, could you squash your commits (fine to collapse mine too).

**Comment by erjohnso** [comment]
@larsla - if you're OK with these tests, I can go ahead and do the cleanup/merge.

**Comment by erjohnso** [comment]
Thanks again for this @larsla!

**Pull request closed without merging**
