### PR TITLE
Merge tooling config into pyproject

### PR DESCRIPTION
**Pull request by rsnk96**
### Description
This is a housekeeping MR, meant to simplify the project complexity at root. Tooling and CQ config files (bandit, py-codecoverage, pylint, mypy, pytest) have been moved into `pyproject.toml`, since it is becoming the standard way of defining all tooling-config in python (Ref: https://peps.python.org/pep-0621/)

NOTE: `tox.ini` has been left as-is, since it was larger, and probably can be addressed in a separate MR (so that this MR is simple to review). Additionally, `flake8` config file has also been left as-is, as [they have decided](https://github.com/PyCQA/flake8/issues/234) to not yet officially support pyprojecte

### Status

Done, ready for review

### Checklist (tick everything that applies)

- [x] ~[Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)~ (No code changes made)
- [ ] Documentation
- [x] ~[Tests](http://libcloud.readthedocs.org/en/latest/testing.html)~ (No functionality added)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by Kami** [comment]
Thanks for this change :+1: 

I will go ahead and test it locally and if everything looks fine, merge it into trunk.

**Comment by Kami** [comment]
I tested it locally and everything except mypy change seems to be looking fine. I'll dig in why mypy config is not working as it should and hopefully fix it.

Eventually we can also move package metadata from setup.py into pyproject.toml.

**Comment by Kami** [comment]
I think 739d0538c9e36371779d74225b260c810600ffe4 should do the trick for the MyPy config migration.

**Comment by Kami** [comment]
Needed two more small fixes for coverage and bandit (cd0129678f52ad44ed9e130bfe19d405ce75ae70, a39b6409131416c1448a64915af8f98c75137eb3), but everything appears to be working / passing now.

**Review by Kami — APPROVED** [review]

**Comment by Kami** [comment]
Merged into trunk. Thanks!

**Comment by rsnk96** [comment]
Glad to see it merged @Kami ! :)

Had two quick follow up queries, would appreciate it if you could help me out:
1. Do you think a vendor-neutral queue API would make sense here? (Ref: https://github.com/apache/libcloud/issues/1786). I started working on this merged housekeeping MR because I was looking to eventually contribute a queue API.
2. If I'm contributing more code here, any apache-project specific practices I've to be aware of, apart from signing the ICLA (my first apache project ;))?

**Comment by Kami** [comment]
@rsnk96 

1. Yeah, I think it makes sense. But since queuing APIs are usually quite poll heavy, I think it also makes sense to expse async API in addition to the sync one.
2. ICLA is a good start. We have some project specific information here - https://libcloud.readthedocs.io/en/stable/development.html

**Pull request merged**
