### PR TITLE
LIBCLOUD-169: Refactor AWS connection and response to reduce code duplication

### PR DESCRIPTION
**Pull request by Jc2k**
As promised in the elb pr, here is a follow up patch to reduce code duplication. I haven't run pep8 over it yet, but the tests pass. I'm AFK for a few days, but wanted to at least get something up here.

I think this error parsing can be applied to the EC2 backend too but wanted to get some feedback on the general approach first.

### CODE REVIEW

**Comment by Kami** [comment]
General approach looks good to me.

**Comment by Kami** [comment]
It might take a while to get this fully reviewed and merged, because I also plan to test everything manually.

Currently we don't have a complete test coverage for all the authentication stuff so a problem could easily slip through and cause a regression.

One problem I see immediately is `version` attribute not being set in the Route53 connection class which would cause authentication to fail.

**Comment by Jc2k** [comment]
Good idea.

That specific example - Route53 doesn't use SignedAWSConnection (yay for consistent authentication API's amazon!!) so doesn't need `self.version`.

**Comment by Kami** [comment]
@Jc2k Also, I'm already on it so no need for you to update the PR at the moment.

**Comment by Kami** [comment]
@Jc2k I've tested it, made some changes and merged patch into master. Thanks!

**Pull request closed without merging**
