### PR TITLE
[gce] ex_create_network can have NoneType routing_mode

### PR DESCRIPTION
**Pull request by danhunsaker**
Check for that before trying string operations on it.

### CODE REVIEW

**Comment by pquentin** [comment]
The docstring says:

        :param  routing_mode: Create network with 'Global' or 'Regional'
                              routing mode for BGP advertisements.
                              Defaults to 'Regional'
        :type   routing_mode: ``str`` or ``None``

Maybe the correct fix is to set routing_mode to `Regional` if it's None?

**Comment by danhunsaker** [comment]
That default happens on Google's end rather than ours, and they seem to prefer not sending a value at all unless you have an explicit preference for one or the other. But that's certainly an option as well. I was just opting for actually supporting `None`, as the docstring also indicates is valid.

**Comment by pquentin** [comment]
Thanks, that makes sense, I'll merge this when I have the chance.

**Comment by pquentin** [comment]
Thanks! Merged in trunk. ✨

**Pull request closed without merging**
