### PR TITLE
Add a tags parser to ecs driver compute list_nodes method

### PR DESCRIPTION
**Pull request by dimasmamot**
### Description

- Add `_get_tags` method to parse list of Tags//Tag from tags element
- Insert parsed `tags` as node.extra

### Status

- work in progress

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by Kami** [comment]
Thanks for the contribution.

The changes look good to me, but we need some unit tests for those changes.

**Comment by dimasmamot** [comment]
cool, will add test soon

**Review by alivx — APPROVED** [review]

**Comment by Kami** [comment]
@alivx I see you approved this PR.

Would you mind finishing it up (adding test cases, syncing changes with latest trunk) so we can merge it into trunk?

**Comment by Kami** [comment]
Thanks for your contribution.

Since this PR hasn't been updated for a long time, I will close it.

If the change still relevant please feel free to re-open this PR (and in that case, please also sync it with the latest trunk).

**Pull request closed without merging**
