### PR TITLE
C4 instance type support

### PR DESCRIPTION
**Pull request by amitlalani**

### CODE REVIEW

**Comment by tonybaloney** [comment]
looks good, will merge

**Comment by tonybaloney** [comment]
@amitofs any further commits?

**Comment by tonybaloney** [comment]
Pricing also needs to be updated as per https://github.com/apache/libcloud/pull/634

**Comment by tonybaloney** [comment]
nw, @kami already did it on the last sync, the prices are already there.

**Comment by Kami** [comment]
@tonybaloney Just FYI, looks like this (29e33873d9e072f75f407cbf32f0f09c5cf3b875) slipped through since the patch was merged before @amitofs updated the PR.

In any case, it's fixed now :)

**Pull request closed without merging**
