### PR TITLE
[compute] [azure_arm] `app create`; `sp create`; `role assignment create`

### PR DESCRIPTION
**Pull request by SamuelMarks**
### Description

The goal is to replace the first 3 CLI commands that require the Azure client installed, with Apache Libcloud code: http://libcloud.readthedocs.io/en/latest/compute/drivers/azure_arm.html

### Status
- work in progress

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by pquentin** [comment]
Thanks! The build will need to pass and we'll need tests, too.

**Comment by mitar** [comment]
This would be awesome to have.

**Comment by Kami** [comment]
First thank you for your contribution.

This PR is very old and out of date now so I will go ahead and close it.

If it's still relevant, please sync your changes with the latest master / trunk and open a new PR. Thanks!

**Comment by SamuelMarks** [comment]
Pushed 666 commits from `apache:trunk` into `offscale:azure_arm_patches`; hope that doesn't mean anything!

**Comment by mitar** [comment]
I think you have to open a new PR?

**Pull request closed without merging**
