### PR TITLE
[LIBCLOUD-907] Added DNS driver for OnApp

### PR DESCRIPTION
**Pull request by hackedunit**
### Description

* Implements driver methods for manipulating DNS zones and records on an OnApp host
* Includes tests and documentation

JIRA ticket: https://issues.apache.org/jira/browse/LIBCLOUD-907
Provider API: https://docs.onapp.com/display/52API/DNS+Zones

### Status

- done, ready for review

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) 
- [x] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes)

### CODE REVIEW

**Comment by tonybaloney** [comment]
thanks @hackedunit there are some CI errors to check out first https://travis-ci.org/apache/libcloud/builds/215039908

**Comment by tonybaloney** [comment]
@hackedunit did you mean to close the PR? It won't get reviewed any further if so

**Comment by hackedunit** [comment]
@tonybaloney I will open it with a single commit once I fix the issue with the failing builds - just can't figure out what is really failing it. `sudo tox` passes locally and `sudo tox -e docs` gives me new errors.

**Comment by tonybaloney** [comment]
I would hazard a guess and say you added the onapp driver manually to the DNS supported providers table. 
It's supposed to be generated by the script in contrib. 
run `make HTML` inside the doc folder

**Comment by hackedunit** [comment]
Thanks @tonybaloney. It was actually a duplicate URL reference - fixed it and issued a new pull request here #1017

**Pull request closed without merging**
