### PR TITLE
DimensionData: Adding ability to remove a backup clients + small updates

### PR DESCRIPTION
**Pull request by jadunham1**
Added a new method ex_remove_client_from_target
After comment from @tonybaloney noticed that the translation functions should be privatized instead, can't find any use outside of the classes currently, so I privatized them.  Helps the code look cleaner.
Added both positive/negative test coverage around new backup call.
Added test coverage around privatized translation functions

### CODE REVIEW

**Comment by tonybaloney** [comment]
:+1: LGTM

**Comment by tonybaloney** [comment]
need to investigate the use of basestring. the libcloud one isn't a superclass of unicode and str like it is in the std library. which is annoying. @Kami is that on purpose?

**Comment by jadunham1** [comment]
I'm also not a huge fan as I have to make sure it isn't unicode when going in.  It was what we were using as conventions before so I kept with it as the code was this way.

**Comment by tonybaloney** [comment]
The tests are looking great now @jadunham1

**Pull request closed without merging**
