### PR TITLE
Trunk

### PR DESCRIPTION
**Pull request by juancarlosm**
Replace common/linode.py constant LINODE_PLAN_IDS by updated plan ids get function. Currently there are no plan 512 or 768, and plan id 3 is returns 1024 plan, but now is 2048

### CODE REVIEW

**Comment by Kami** [comment]
This patch seems reasonable to me. What do other people think - @jedsmith.

@JuanCarlosM Can you please open a ticket at https://issues.apache.org/jira/browse/LIBCLOUD and attach a final patch there?

Thanks

**Comment by juancarlosm** [comment]
yes, of course. thanks

**Comment by jedsmith** [comment]
I think it would be better if it remained static, as you're now incurring an (agreed, minimal) overhead for what ultimately is static data; for perspective, that data hasn't changed since I wrote it in 2010, and I doubt it will change again any time soon. If the overhead is genuinely minimal, I guess it's fine, but I think you're adding a bit of startup delay to the driver unnecessarily.

I had this on my list for this weekend, so thanks for getting to it, either way!

**Comment by Kami** [comment]
@jedsmith Thanks for looking into this.

**Comment by Kami** [comment]
(just doing some pull request cleanup)

@JuanCarlosM - Those changes are not relevant anymore, can you please close this pull request?

Thanks!

**Pull request closed without merging**
