### PR TITLE
doc: Update documentation for AuroraCompute

### PR DESCRIPTION
**Pull request by wido**
Add an example on how to instantiate a driver and where to find
the API en Secret key.

### CODE REVIEW

**Comment by wido** [comment]
The build seems to fail, but I don't think it's related to this PR?

**Comment by sebgoa** [comment]
@wido why do you say its failing, Travis seems to have passed.

**Comment by wido** [comment]
@runseb The build has stabilized, no more issues :)

**Comment by Kami** [comment]
Merged, thanks.

**Pull request closed without merging**
