### PR TITLE
Fixed spelling errors

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by allardhoeve** [comment]
Thanks, that's better :wink:

**Comment by Kami** [comment]
@allardhoeve do you want to merge this one?

**Comment by Kami** [comment]
@allardhoeve Thanks - next time please also use `--signoff` git argument.

Ideally, you would download the patch (`wget https://github.com/apache/libcloud/pull/480.patch`) and merge / apply it using `git am` as described at https://libcloud.readthedocs.org/en/latest/committer_guide.html#applying-a-patch

**Comment by allardhoeve** [comment]
Actually, I did do that, kinda. Ik merged pull/480/HEAD into trunk.

But yes, will use --signoff next time.

Also, I typed closed, not closes, it did not close the Github PR properly.

**Comment by Kami** [comment]
@allardhoeve Yep (re using git am instead of merge), this way we can keep flat history and it's also easier to rebase / squash commits if needed.

**Comment by Kami** [comment]
@allardhoeve As far as closed / closes keywords go, I actually thought both should work :)

**Pull request merged**
