### PR TITLE
Add c5d and m5d node types to AWS eu-central-1

### PR DESCRIPTION
**Pull request by cure**
### Description

The AWS Frankfurt region (eu-central-1) now has c5d and m5d node types available. Make them accessible in libcloud.

### Status

Done, ready for review.

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by pquentin** [comment]
Hello @cure, and thank you for your interest in the project.

This file is generated and should not be edited manually. We use `python contrib/scrap-ec2-sizes.py > libcloud/compute/constants.py` to generate it. If the script fails to add your changes, that means we need to update the script. :)

**Comment by cure** [comment]
Thanks @pquentin. I ran `python contrib/scrap-ec2-sizes.py > libcloud/compute/constants.py` and it does indeed add the c5d/m5d types for eu-central-1. Is this script run manually? Or is it run before each release? Should I update this pull request with the output of the command?

**Comment by pquentin** [comment]
@cure Thank you! The script is indeed [run before each release](https://libcloud.readthedocs.io/en/latest/committer_guide.html#making-a-release-for-release-managers). (To be fair, it is so recent that we never used it in a real release!).

Since we're planning to release libcloud soon, it would be nice to update the PR to contain the output of this command, yes!

**Comment by cure** [comment]
@pquentin no problem, I've pushed an updated branch. I see that the script introduces a spurious trailing space on most of the lines it changed.

**Comment by pquentin** [comment]
Oh, that's bad! It seems surprising that the script did that. Do you think you can remove them, maybe manually for now?

**Comment by cure** [comment]
Sure thing, done.

**Comment by pquentin** [comment]
@cure Thanks! Merged in trunk. ✨

**Pull request closed without merging**
