### PR TITLE
[LIBCLOUD-936] fixed AWS ALB/ELB driver init method to instantiate ne…

### PR DESCRIPTION
**Pull request by lrvan**
### Description

AWS ELB/ALB Driver connection object initialization is broken. 

Error:
`/Users/irvan/py27venv/bin/python test_token.py
Traceback (most recent call last):
  File "test_token.py", line 33, in <module>
    data = driver.list_balancers()
  File "/Users/irvan/Repos/GIT/github/libcloud/libcloud/loadbalancer/drivers/elb.py", line 68, in list_balancers
    data = self.connection.request(ROOT, params=params).object
  File "/Users/irvan/Repos/GIT/github/libcloud/libcloud/common/base.py", line 603, in request
    headers=headers, stream=stream)
  File "/Users/irvan/Repos/GIT/github/libcloud/libcloud/http.py", line 215, in request
    verify=self.verification
  File "/Users/irvan/py27venv/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/irvan/py27venv/lib/python2.7/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/Users/irvan/py27venv/lib/python2.7/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='elasticloadbalancing.%s.amazonaws.com', port=443): Max retries exceeded with url: /2012-06-01/?Action=DescribeLoadBalancers&Version=2012-06-01 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10760f4d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))`

Issue:
https://issues.apache.org/jira/browse/LIBCLOUD-936

### Status

done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by lrvan** [comment]
build [3789.9|https://travis-ci.org/apache/libcloud/jobs/262180991] failure seems to be not related to the change introduced by PR

build [3789.10|https://travis-ci.org/apache/libcloud/jobs/262180994] failed with some tests invocation error:
...................................................................................ERROR: InvocationError: '/home/travis/build/apache/libcloud/.tox/pypypy/bin/python setup.py test'
___________________________________ summary ____________________________________
ERROR:   pypypy: commands failed

build [3789.11|https://travis-ci.org/apache/libcloud/jobs/262180996] failed with an error related to test environment setup:
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: setuptools-scm>=1.15.0

the rest are fine.

**Comment by lrvan** [comment]
build [3789.9](https://travis-ci.org/apache/libcloud/jobs/262180991) failure seems to be not related to the change introduced by PR

build [3789.10](https://travis-ci.org/apache/libcloud/jobs/262180994) failed with some tests invocation error:
...................................................................................ERROR: InvocationError: '/home/travis/build/apache/libcloud/.tox/pypypy/bin/python setup.py test'
___________________________________ summary ____________________________________
ERROR:   pypypy: commands failed

build [3789.11](https://travis-ci.org/apache/libcloud/jobs/262180996) failed with an error related to test environment setup:
  File "/home/travis/virtualenv/pypy3-2.4.0/site-packages/pkg_resources/__init__.py", line 805, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: setuptools-scm>=1.15.0

the rest are fine.

**Comment by tonybaloney** [comment]
@lrvan the tests should pass now

**Comment by tonybaloney** [comment]
Merging 👍

**Pull request closed without merging**
