### PR TITLE
Add support for GCE list paging and filtering

### PR DESCRIPTION
**Pull request by verb**
GCE will return a maximum of 500 resources in a single list. This change
adds an iterator that allows filtering and/or paging of list results.

### CODE REVIEW

**Comment by Kami** [comment]
Will dig in ASAP.

On a related note - we already have an establish pattern for handling paginated collections which should probably also work here. See https://github.com/apache/libcloud/blob/trunk/libcloud/dns/drivers/zerigo.py#L149 for an example.

**Comment by erjohnso** [comment]
Ah, good point. Reminded me that the Google DNS driver also uses generators: https://github.com/apache/libcloud/blob/trunk/libcloud/dns/drivers/google.py

**Comment by verb** [comment]
Ah, didn't see that. It looks like this would be the first time iterate_\* is used in the compute driver.

It would be pretty easy to overlay the iterate_\* functions on top of GCEList if my underlying approach is still sound. This would keep the filter functionality available in ex_list().

Alternatively we could establish a pattern for filter, too.

**Comment by verb** [comment]
friendly ping and just checking in to make sure nothing is blocked on me.

**Comment by Kami** [comment]
@erjohnso can you please review this one and take it across the finish line?

**Comment by Kami** [comment]
@verb Sorry for the delay. I have quickly glanced over it and it looks good to me, but I haven't done any testing.

**Comment by erjohnso** [comment]
Sorry for the delay, @verb!  Thanks!!

**Pull request closed without merging**
