### PR TITLE
Issue LIBCLOUD-484: dns driver bug fix - list_records

### PR DESCRIPTION
**Pull request by dineshbhoopathy**
https://issues.apache.org/jira/browse/LIBCLOUD-484

### CODE REVIEW

**Comment by Kami** [comment]
@diablob The change looks good, thanks.

On a related note - do you have any link to the HostVirual API documentation? Last time I was looking for it, but I couldn't find it.

**Comment by Kami** [comment]
Patch merged into trunk, thanks!

**Comment by dineshbhoopathy** [comment]
@Kami Currently the API documentation requires being logged in.

**Comment by Kami** [comment]
This pull request can be closed now.

**Comment by dineshbhoopathy** [comment]
Thanks!

**Pull request closed without merging**
