### PR TITLE
[LIBCLOUD-637] Map param ex_blockdevicemappings to block_device_mapping_v2

### PR DESCRIPTION
**Pull request by gertjanol**
Add support the for the block_device_mapping_v2-parameter in [Compute API v2 extensions](http://developer.openstack.org/api-ref-compute-v2-ext.html#ext-os-block-device-mapping-v2-boot).
https://issues.apache.org/jira/browse/LIBCLOUD-637

### CODE REVIEW

**Comment by allardhoeve** [comment]
bump

**Comment by Kami** [comment]
Hey, sorry for the delay, looks like we some how missed this one.

The change looks good to me, but the build failures need to be fixed.

**Comment by allardhoeve** [comment]
Where do the failures stem from? I couldn't parse the log :smile: It looks like unrelated PEP8 errors?

**Comment by Kami** [comment]
Yep, pep8 / lint violation.

**Comment by allardhoeve** [comment]
Ah, I was thrown off by the 700 or so other `line too long` exceptions that `flake8` reports.

But fixed as requested!

**Comment by allardhoeve** [comment]
bump

**Comment by Kami** [comment]
Merged into trunk. Thanks.

**Pull request closed without merging**
