### PR TITLE
Fixed the loadbalancer method for cloudstack incl tests

### PR DESCRIPTION
**Pull request by jeroendekorte**
Load balancer:
Updated the loadbalancer for Cloudstack since this was not working.

Compute:
Updated the list_images to check if a image size is returned or not. Some templates/images don't have a size.

### CODE REVIEW

**Comment by sebgoa** [comment]
yep, saw it. looks good to me. I can merge it on wednesday..

**Comment by sebgoa** [comment]
LGTM, I applied it. Forgot to close the pull request. @jeroendekorte thanks, can you close the PR.

**Comment by sebgoa** [comment]
@jeroendekorte can you close this. I applied your patch but cannot close the pr on github.

**Comment by jeroendekorte** [comment]
Done, thanks guys!

**Pull request closed without merging**
