### PR TITLE
make CI build faster

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by hutson** [comment]
@PeterDaveHello, your commit message does not explain how your change reduces the build times, or what side-effects it may have on build stability. Could you please update your commit message to include comments on those issues.

**Comment by PeterDaveHello** [comment]
Sure, updated :)

**Comment by Kami** [comment]
A while ago, I timed `git clone ...` and `git clone --depth=1` and there was basically no difference in timings / the difference was negligible.

That's probably because our history is pretty small and simple.

**Comment by hutson** [comment]
It seems, based on limited searching, that Travis CI already sets a clone [depth of 100](https://github.com/travis-ci/travis-ci/issues/617), and that setting limits close to 1 may introduce additional [build instability](https://github.com/Freeseer/freeseer/commit/84252a6afc1465265565dd72d17c0bc438ba0988).

**Pull request closed without merging**
