### PR TITLE
[LIBCLOUD-870] Implement create methods for AWS ALB driver

### PR DESCRIPTION
**Pull request by lrvan**
### Description

1) Implemented AWS ALB driver methods to create application load balancer or its parts:
- create_balancer
- ex_create_balancer
- ex_create_target_group
- ex_register_targets
- ex_create_listener
- ex_create_listener_rule

2) Fixed parameter/field names/types in some methods to be uniform across the driver.
3) Extended \_to\_#object_type# methods to fetch and return additional data about the object from AWS response.

### Status
- done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by tonybaloney** [comment]
@lrvan thanks!

This to be merged after #1089 ?

**Comment by lrvan** [comment]
Hi Anthony,

yes, 1089 goes first.

**Comment by tonybaloney** [comment]
@lrvan the other PR has been merged.

The methods all need docstrings with explanations and types for the keyword arguments. Please see other drivers for examples.

**Comment by lrvan** [comment]
@tonybaloney reworked driver to use classes for listener/rule/target group and added docstrings.

**Comment by Kami** [comment]
First thank you for your contribution.

This PR is very old and out of date now so I will go ahead and close it.

If it's still relevant, please sync your changes with the latest master / trunk and open a new PR. Thanks!

**Comment by lrvan** [comment]
Rebased and created new PR:
https://github.com/apache/libcloud/pull/1349

**Pull request closed without merging**
