### PR TITLE
[LIBCLOUD-682] Add fields for additional OpenStack size information

### PR DESCRIPTION
**Pull request by jimbobhickville**
Adds:
- swap - the amount of swap provisioned for the flavor
- ephemeral_disk - the amount of non-root local storage for the flavor
  (from the OS-FLV-EXT-DATA extension used by Rackspace)
- extra - additional metadata about the flavor
  (from the OS-FLV-WITH-EXT-SPECS extension used by Rackspace)

### CODE REVIEW

**Comment by allardhoeve** [comment]
Hey Greg!

Thanks for contributing! Can you add some unittests to the openstack tests? That way we ensure that this added value keeps working in the future. Thanks!

**Comment by jimbobhickville** [comment]
Oh, derp.  Yes I can.  I'll get the PR updated tomorrow.

**Comment by jimbobhickville** [comment]
I added some tests similar in style to the other openstack tests around it.  Let me know if they are sufficient or you'd like to see more.  Looks like the sizes didn't have much test coverage other than the pricing information, so I added a few other tests in there as well.

**Comment by jimbobhickville** [comment]
@allardhoeve any feedback on the tests I added?

**Comment by allardhoeve** [comment]
Looks good, but will wait for the tests to succeed

**Comment by jimbobhickville** [comment]
Is there a reason they aren't running yet?  It hasn't even tried to start them it seems.

**Comment by allardhoeve** [comment]
Travis is slooooww

**Comment by jimbobhickville** [comment]
More than a day slow?  Wow, ok.

**Comment by allardhoeve** [comment]
Travis CI is not fast. I've seen it be a day or two. Or get stuck. In that case I'll run the tests myself.

**Comment by allardhoeve** [comment]
thanks, merged

**Pull request closed without merging**
