### PR TITLE
Fix blob storage regression

### PR DESCRIPTION
**Pull request by ldipenti**
### Description

Hello,
Here's a fix to allow using azure's blob storage on alternate environments, it seems that the regression was introduced here: https://github.com/apache/libcloud/commit/5352e710350939539878aae879c2bd687f401c3d

### Status

Replace this: describe the PR status. Examples:

- done, ready for review

### Checklist (tick everything that applies)

- [X] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [X] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by pquentin** [comment]
The change itself is nice! But it looks like there are unrelated commits?

**Comment by ldipenti** [comment]
Yes, I'm not sure why. I made this from the same branch as my previous PR https://github.com/apache/libcloud/pull/1100, that I thought it was accepted but it appears to be closed and not merged.
That's odd, I checked the apache.org repo and IIRC I saw the changes merged there.

**Comment by pquentin** [comment]
PR #1100 was definitely merged, but since the GitHub repository is only a mirror of the Apache repo, the accepted PRs are declined and the relevant code is pushed to the Apache repository (http://git.apache.org/libcloud.git/) which then appears on GitHub.

Please rebase your change on top of the trunk branch, and ensure you do not push any merge commits.

**Comment by Kami** [comment]
Thanks.

The change looks good to me, but can you please add corresponding test cases to avoid such regression in the future?

**Comment by ldipenti** [comment]
Thanks for your comments pquentin & Kami, I'll get back to you later addressing this suggestions.

**Comment by Kami** [comment]
I went ahead, merged it and added tests (91d14eaa0d54432e0b047e291279a4f6123314b1, 2a8764b1d4dffaf2217a670323b31cef953d1679, 91ea09116afa5b5e969a6a2184c3a68fc192c485) so in can be included in time for v2.2.1 release.

Thanks again.

**Comment by ldipenti** [comment]
Thanks Kami!

**Pull request merged**
