### PR TITLE
LIBCLOUD-760 malformed xml requests

### PR DESCRIPTION
**Pull request by tonybaloney**
Fixed 2 bugs raised by @EfrenRey where delete Nat rule, edit firewall rule are not containing the right capitalization of Rule in the XML request.

### CODE REVIEW

**Comment by Kami** [comment]
/cc @erjohnso 

I assume you will merge this when rolling out a new 0.19.0 release, right?

**Comment by erjohnso** [comment]
Yes. From the thread on dev, we'll close that vote thread and @tonybaloney is planning on adding some basic tests. That can go in this PR too.

**Comment by tonybaloney** [comment]
@erjohnso these are the required tests to check the request bodies as well for typos. all done

**Comment by erjohnso** [comment]
Outstanding, thank you @tonybaloney!

I'll get this merged in later tonight and start working on the revised 0.19.0 release.

**Pull request closed without merging**
