### PR TITLE
Add support for ec2 ap-east-1

### PR DESCRIPTION
**Pull request by r2ronoha**
### Description

Replace this with the PR description (mention the changes you have made, why
you have made them, provide some background and any references to the provider
documentation if needed, etc.).

For more information on contributing, please see [Contributing](http://libcloud.readthedocs.org/en/latest/development.html#contributing)
section of our documentation.

### Status

Replace this: describe the PR status. Examples:

- work in progress
- done, ready for review

### Checklist (tick everything that applies)

- [X] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [] Documentation
- [X] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by Kami** [comment]
Thanks for the contribution.

Can you please add a corresponding test case for it and confirm ``libcloud/compute/constants/ec2_region_details_complete.py` has been updated by running ``contrib/scrape-ec2-sizes.py`` script?

**Comment by Kami** [comment]
Per my my comment above and in the other PR, ``contrib/scrape-ec2-prices.py`` & ``contrib/scrape-ec2-sizes.py`` files need to be updated and then ``tox -e scrape-ec2-sizes`` command needs to be run.

Otherwise those changes won't have any affect and will get overwritten next time ``tox -e scrape-ec2-sizes`` command runs.

I've done that in 762f0e5623b6f9837204ffe27d825b236c9c9970, re-ran that tox target and committed the changes.

The changes have also been merged into trunk. Thanks for your contribution.

I will also try to add some information on how to handle updating those sizes and pricing data to the developer documentation.

**Comment by Kami** [comment]
I added some developer docs on how to update sizing (+region) and pricing data in 460876539f363b266cc4e01ab76598fa53b711a2.

**Comment by r2ronoha** [comment]
> I added some developer docs on how to update sizing (+region) and pricing data in [4608765](https://github.com/apache/libcloud/commit/460876539f363b266cc4e01ab76598fa53b711a2).

Many thanks for your assistance

**Pull request merged**
