### PR TITLE
Support aws eu-north-1 region (Stockholm) #1369

### PR DESCRIPTION
**Pull request by michaelsembwever**
ref: https://github.com/apache/libcloud/issues/1369

### Status

ready for testing and review.

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [x] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by Kami** [comment]
LGTM, thanks for the contribution.

Just a heads up, in the future we plan to the move to the single driver class + "region" argument approach - #1366.

**Comment by michaelsembwever** [comment]
@Kami , i'm aware, and was kinda disappointed when i saw the aws regions hardcoded. I put this PR in as I need it in production in a hurry. Otherwise, although my python isn't fantastic, I'll see if i find some time later on to provide the PR for #1366

**Comment by Kami** [comment]
@michaelsembwever I will try to have a look at moving S3 driver to single region model soon.

Sadly the code is a bit convoluted in regards to how class variables and class instance variables are used so there are some edge cases which need to be taken care correctly.

**Comment by Kami** [comment]
Merged in via #1371. Thanks again for the contribution.

**Pull request closed without merging**
