### PR TITLE
openebula 3.8 support

### PR DESCRIPTION
**Pull request by gza**
changes:
- sizes listing need sub-request
- support for plain_auth (should need review)

### CODE REVIEW

**Comment by Kami** [comment]
Current code looks good, but it's missing tests.

**Comment by gza** [comment]
I had to change my plain_auth code because the creation of OpenNebulaConnection_3_8 did brake le mock connection hook.
Hope I did well

**Comment by Kami** [comment]
Can you please create a new JIRA ticket and attach a final patch there - https://issues.apache.org/jira/browse/LIBCLOUD

**Comment by gza** [comment]
Submitted to https://issues.apache.org/jira/browse/LIBCLOUD-295

**Pull request closed without merging**
