### PR TITLE
Fix EBS volume encryption

### PR DESCRIPTION
**Pull request by mermoldy**
### Status

- done, ready for review

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

### CODE REVIEW

**Comment by tonybaloney** [comment]
thanks for the contribution @mermoldy.
the fixtures have been updated in another PR, so there's now a merge conflict in your PR (just on the XML files). 

You could either remove them from the change set and pull the changes back in or resolve conflicts with a merge commit.

**Comment by mermoldy** [comment]
@tonybaloney I left the small fix for `ex_encrypted` parameter

**Comment by pquentin** [comment]
@mermoldy Thank you for your contribution! Sorry that this dropped out of the radar.

When this [feature was first introduced by @ViktorOgnev](https://github.com/apache/libcloud/pull/729/files), no tests were added, and I would like to fix this this time. Could you add a test with a fixture that tests that encryption works with both `ex_encrypted` and `ex_kms_key_id`?

Thank you!

**Comment by mermoldy** [comment]
@pquentin Ok, i added a test for `ex_encrypted`/`ex_kms_key_id`.

**Comment by pquentin** [comment]
Thanks! I'll review it when I can, probably tomorrow.

**Comment by pquentin** [comment]
Thank you @mermoldy. This has been merged in trunk. ✨

**Pull request closed without merging**
