### PR TITLE
Updated HP Cloud example

### PR DESCRIPTION
**Pull request by CaptTofu**
HP Cloud is now using Havana and is no longer using 3-AZs for new users. For older users it is, but that's really deprecated)

### CODE REVIEW

**Comment by Kami** [comment]
Looks good to me.

/cc @mgogoulos

**Comment by CaptTofu** [comment]
I just fixed the pep8/pyflake error (trailing space) and resubmitting.

**Comment by CaptTofu** [comment]
tests pass

**Comment by Kami** [comment]
The pull request looks kinda messed up. Besides that, it looks good. I'll go ahead and merge it.

Next time please create a separate branch for each of your changes and don't modify trunk directly. This will make it easier for both of us.

**Comment by mgogoulos** [comment]
On my HP Cloud I'm still using AZ 1-3 for US West, but as CaptTofu says this is deprecated now, so no problem!

**Comment by CaptTofu** [comment]
Sorry about the trunk issue. I was mixing my work up here with what I had for salt-cloud. Yeah, my original HP cloud account I still am able to use the old Essex-based cloud, but the emphasis is on the new Havana-based cloud.

**Comment by Kami** [comment]
Btw, this patch has been merged so the PR can be closed now.

Thanks.

**Comment by Kami** [comment]
@CaptTofu You might be interested in this:
- a91147f2b5d820bf2e4c2717b8fb4352d1491502
- https://libcloud.readthedocs.org/en/latest/compute/drivers/hpcloud.html

**Pull request closed without merging**
