### PR TITLE
Improve k8s drivers

### PR DESCRIPTION
**Pull request by ckaraneen**
- Improve and extend Kubernetes driver
- Fix and extend GKE driver
- Add EKS driver
- Fix, improve, extend or add Kubernetes, GKE, EKS driver tests

### CODE REVIEW

**Comment by Kami** [comment]
@ckarageorgkaneen @d-mo I see the diff is quite large - are all the changes backward incompatible (I'm talking mostly about the changes to the common Google and AWS connection code).

And how should we approach reviewing and merging this? Are the changes already ready for a review or are they still WIP?

In ideal world, those changes would be split into multiple PRs, but I know that would mean more work on your side, re-organizing all those changes.

So if we are confident about the tests coverage and all the changes being backward compatible, we can also try to review it in the current form :)

**Comment by Kami** [comment]
And I assume this PR supersedes changes in https://github.com/apache/libcloud/pull/1423, so I can close that PR?

**Comment by d-mo** [comment]
Hi @Kami,

Sure, we will split this up in a bunch smaller PR's, hopefully this week.
@dimgal1 is currently working on it. Along with @ckarageorgkaneen they have extended the drivers further.

Feel free to close this PR.

**Comment by Kami** [comment]
@d-mo Great, thanks.

**Pull request closed without merging**
