### PR TITLE
Issue LIBCLOUD-489: api end point change

### PR DESCRIPTION
**Pull request by dineshbhoopathy**
https://issues.apache.org/jira/browse/LIBCLOUD-489

### CODE REVIEW

**Comment by Kami** [comment]
Can you please provide some kind of reference for this change (API docs, blog post or similar)?

**Comment by dineshbhoopathy** [comment]
@Kami Currently the API documentation requires being logged in. The old url will continue to work, however as it is being phased out we are submitting the patch and will make an announcement once it is ready so that it can be included.

**Comment by Kami** [comment]
@diablob OK, sounds good.

I didn't know you work for HostVirtual. Usually, if patch comes from a 3rd party person I like to verify it against documentation or some other reference.

**Comment by Kami** [comment]
I've merged patch into trunk.

There were some lint issues which I have fixed. Next time make sure you run `tox -e lint` and fix any outstanding lint issues.

Thanks!

**Comment by dineshbhoopathy** [comment]
@Kami . Thanks! I suspect those lint issues were from my vim environment. I thought it already checked for pep8 too. suggest any good vim plugin ? 

I'll remember to run tox.

**Comment by Kami** [comment]
I use a `python_flake8` vim plugin (https://github.com/nvie/vim-flake8) which runs flake8 on a Python file every time it's saved.

It worth nothing that this plugin uses default flake8 setting and for libcloud we use slightly less restrictive settings (we allow longer lines in the test files). This means that the plugin might sometimes report violations while `tox -e lint` won't report any.

**Comment by Kami** [comment]
Also, this pull request can be closed now.

**Comment by dineshbhoopathy** [comment]
@Kami , thanks, I moved from python_flake8 to syntastic ( https://github.com/scrooloose/syntastic ) recently and didn't realize I had to enable it in .vimrc as let g:syntastic_python_checker = 'pylint'. Hope this will solve the issue.

Closing this pull request and thanks again for merging it

**Pull request closed without merging**
