### PR TITLE
EC2 support for AWS Seoul region

### PR DESCRIPTION
**Pull request by encyphered**
- Fixed signature version of AWS Seoul region to 4 due to that does not support
- Added provider and driver for region.

### CODE REVIEW

**Comment by tonybaloney** [comment]
Thanks @encyphered do you have instances deployed in Seoul? Amazons press release said a subset of instance sizes for EC2 was supported, is this correct?

**Comment by encyphered** [comment]
@tonybaloney Yes, Amazon announced only T2, M4, C4, I2, D2, and R3 was supported. HS1 is not supported

**Comment by tonybaloney** [comment]
thanks. LGTM +1

**Comment by Kami** [comment]
Thanks for the PR.

Does the new region only support new signature version 4? I'm asking because right now, IIRC, we only support signature version 4 for HTTP GET methods in Libcloud which means we should use 2 if it's still supported (otherwise non GET operations won't work).

**Comment by tonybaloney** [comment]
I added POST request support for v4 about a month ago 

Sent from Outlook Mobile

On Wed, Jan 27, 2016 at 1:55 AM -0800, "Tomaz Muraus" notifications@github.com wrote:

Thanks for the PR.

Does the new region only support new signature version 4? I'm asking because right now, IIRC, we only support signature version 4 for HTTP GET methods in Libcloud which means we should use 2 if it's still supported (otherwise non GET operations won't work).

**Comment by Kami** [comment]
@tonybaloney Ah, nice! :)

I totally missed that.

**Pull request closed without merging**
