### PR TITLE
Issue LIBCLOUD-459: Support region without zone in GCE.

### PR DESCRIPTION
**Pull request by charly37**
try a fix for : LIBCLOUD-459 
First time I try to share a change so I hope I do it well...

### CODE REVIEW

**Comment by Kami** [comment]
Thanks for the pull request.

I'll ping Rick and Eric since they have more experience with GCE driver than I do. They will be able to help you better and suggest the best approach to take to fix this issue.

/cc @wrigri @erjohnso

**Comment by wrigri** [comment]
@charly37 
Looks good to me.  I'll let @Kami follow up with what needs to be done to get it merged in.

**Comment by Kami** [comment]
@charly37 I've squashed the commits and merged patch into trunk. Thanks for the patch and thanks @wrigri for the review.

P.S. @charly37 While merging the patch I have noticed you didn't set up your git author name and email address. This time I've manually added "patch by" line to the commit message, but next time please set this up so we can correctly preserve the commit authorship. You can find information on how to do that at http://git-scm.com/book/en/Getting-Started-First-Time-Git-Setup#Your-Identity

**Comment by Kami** [comment]
@charly37 also, this pull request can be closed now.

**Pull request closed without merging**
